begin;
create or replace function private.build_driver_offers(p_request_id uuid)returns void language plpgsql security definer set search_path='' as $$
declare req public.delivery_requests;o public.orders;trust public.customer_trust_profiles;cfg public.driver_reputation_config;signals text[]:='{}';ranked record;completed int:=0;
begin select * into req from public.delivery_requests where id=p_request_id for update;select * into o from public.orders where id=req.order_id;
 if o.customer_id is null then signals:=array_append(signals,'Cliente externo, sin historial vinculado');else select * into trust from private.refresh_customer_trust(o.customer_id);completed:=coalesce(trust.orders_completed,0);if completed=0 then signals:=array_append(signals,'Cliente nuevo, sin historial de entregas');end if;end if;
 select * into cfg from public.driver_reputation_config where id='main';if extract(hour from o.created_at at time zone'America/Mexico_City')>=cfg.night_start_hour then signals:=array_append(signals,'Entrega nocturna');end if;if lower(o.payment_method)like'%efectivo%'then signals:=array_append(signals,'Pago en efectivo');end if;if o.total>=cfg.high_value_threshold then signals:=array_append(signals,'Pedido de valor elevado');end if;
 if o.customer_id is null or not exists(select 1 from public.orders p where p.customer_id=o.customer_id and p.status='delivered'and p.id<>o.id and lower(trim(p.address->>'address'))=lower(trim(o.address->>'address')))then signals:=array_append(signals,'Dirección sin entregas previas');end if;
 update public.delivery_requests set safety_signals=to_jsonb(signals),safety_level=case when cardinality(signals)>=2 then'additional_precautions'else'standard'end,requires_confirmation=cardinality(signals)>=3 where id=p_request_id;delete from public.driver_offers where request_id=p_request_id;
 for ranked in with candidates as(select c.id,coalesce(m.driver_score,50)driver_score,coalesce(rc.priority_bonus,0)rank_bonus,coalesce(m.trips_7_days,0)recent,(select count(*)from public.delivery_assignments a where a.courier_id=c.id and a.status not in('delivered','cancelled'))active_count,least(20,greatest(0,extract(epoch from(now()-coalesce(m.last_delivery_at,c.created_at)))/3600))fairness from public.couriers c left join public.driver_metrics m on m.courier_id=c.id left join public.driver_rank_configs rc on rc.id=m.rank_id where c.active),r as(select *,round(driver_score*.45+rank_bonus+fairness+(3-active_count)*8-recent*1.5-active_count*12,2)priority,row_number()over(order by driver_score*.45+rank_bonus+fairness+(3-active_count)*8-recent*1.5-active_count*12 desc,id)position from candidates where active_count<3)select * from r loop insert into public.driver_offers(request_id,courier_id,round,dispatch_priority_score,offered_at,expires_at,excluded_from_acceptance_rate)values(p_request_id,ranked.id,case when ranked.position<=cfg.first_round_size then 1 when ranked.position<=cfg.first_round_size+cfg.second_round_size then 2 else 3 end,ranked.priority,req.requested_at+case when ranked.position<=cfg.first_round_size then interval'0 seconds'when ranked.position<=cfg.first_round_size+cfg.second_round_size then make_interval(secs=>cfg.first_round_seconds)else make_interval(secs=>cfg.first_round_seconds+cfg.second_round_seconds)end,req.requested_at+interval'15 minutes',cardinality(signals)>=2);end loop;
end$$;

create or replace function private.request_driver_impl(p_order_id uuid,p_pay numeric,p_pickup_address text)returns public.delivery_requests language plpgsql security definer set search_path='' as $$declare o public.orders;r public.delivery_requests;begin if not private.is_admin()then raise exception'ADMIN_REQUIRED';end if;select * into o from public.orders where id=p_order_id for update;if not found or o.delivery_type<>'delivery'or o.status<>'ready'then raise exception'ORDER_NOT_READY_FOR_DELIVERY';end if;perform private.refresh_driver_metrics(id)from public.couriers where active;insert into public.delivery_requests(order_id,pay,pickup_address)values(p_order_id,greatest(o.driver_pay,0),trim(p_pickup_address))on conflict(order_id)do update set status='requested',pay=greatest(o.driver_pay,0),pickup_address=excluded.pickup_address,assigned_at=null,requested_at=now(),updated_at=now()where public.delivery_requests.status='cancelled'returning * into r;if r.id is null then select * into r from public.delivery_requests where order_id=p_order_id;end if;if r.status='requested'and not exists(select 1 from public.driver_offers where request_id=r.id and status='offered')then perform private.build_driver_offers(r.id);end if;update public.orders set published_at=now()where id=p_order_id;return r;end$$;

create or replace function private.admin_cancel_driver_search_impl(p_order_id uuid)returns void language plpgsql security definer set search_path='' as $$declare r public.delivery_requests;begin if not private.is_admin()then raise exception'ADMIN_REQUIRED';end if;select * into r from public.delivery_requests where order_id=p_order_id for update;if not found or r.status<>'requested'then raise exception'DELIVERY_SEARCH_NOT_ACTIVE';end if;if exists(select 1 from public.delivery_assignments where request_id=r.id and status not in('cancelled','delivered'))then raise exception'DELIVERY_ALREADY_ASSIGNED';end if;update public.delivery_requests set status='cancelled',updated_at=now()where id=r.id;update public.driver_offers set status='expired',responded_at=now()where request_id=r.id and status='offered';update public.orders set published_at=null where id=p_order_id;insert into public.audit_events(actor_id,event_type,entity_type,entity_id,reason)values(auth.uid(),'driver_search_cancelled','order',p_order_id::text,'Cancelada por administrador');end$$;
create or replace function public.admin_cancel_driver_search(p_order_id uuid)returns void language sql security invoker set search_path='' as $$select private.admin_cancel_driver_search_impl(p_order_id)$$;
revoke all on function public.admin_cancel_driver_search(uuid),private.admin_cancel_driver_search_impl(uuid)from public,anon;grant execute on function public.admin_cancel_driver_search(uuid)to authenticated;
commit;
