begin;

create table if not exists public.promotion_redemptions (
  id uuid primary key default gen_random_uuid(),
  promotion_id uuid not null references public.promotions(id),
  customer_id uuid not null references public.customers(id),
  order_id uuid references public.orders(id),
  status text not null default 'reserved' check (status in ('reserved','used','cancelled')),
  created_at timestamptz not null default now(),
  used_at timestamptz,
  cancelled_at timestamptz
);
create unique index if not exists promotion_redemptions_one_active
  on public.promotion_redemptions(promotion_id,customer_id) where status in ('reserved','used');
alter table public.promotion_redemptions enable row level security;
drop policy if exists "customers_read_own_promotion_redemptions" on public.promotion_redemptions;
drop policy if exists "admin_promotion_redemptions_all" on public.promotion_redemptions;
create policy "customers_read_own_promotion_redemptions" on public.promotion_redemptions for select to authenticated using ((select auth.uid())=customer_id);
create policy "admin_promotion_redemptions_all" on public.promotion_redemptions for all to authenticated using (private.is_admin()) with check (private.is_admin());

create table if not exists public.external_contacts (
 id uuid primary key default gen_random_uuid(), name text not null, phone text not null,
 normalized_phone text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.external_contacts enable row level security;
drop policy if exists "admin_external_contacts_all" on public.external_contacts;
create policy "admin_external_contacts_all" on public.external_contacts for all to authenticated using (private.is_admin()) with check (private.is_admin());

alter table public.promotions add column if not exists gift_product_id text references public.products(id);
alter table public.promotions add column if not exists gift_size_name text;
alter table public.promotions add column if not exists max_uses_per_customer integer not null default 1 check (max_uses_per_customer between 1 and 20);
alter table public.orders alter column customer_id drop not null;
alter table public.orders add column if not exists external_contact_id uuid references public.external_contacts(id);
alter table public.orders add column if not exists order_source text not null default 'app' check (order_source in ('app','whatsapp','messenger','manual','other'));
alter table public.orders add column if not exists created_by uuid references auth.users(id);
alter table public.orders add column if not exists published_at timestamptz;
alter table public.orders drop constraint if exists orders_customer_identity;
alter table public.orders add constraint orders_customer_identity check (num_nonnulls(customer_id,external_contact_id)=1) not valid;
alter table public.orders validate constraint orders_customer_identity;
alter table public.order_items add column if not exists item_type text not null default 'product' check (item_type in ('product','reward','promotion_gift'));
alter table public.order_items add column if not exists promotion_id uuid references public.promotions(id);
alter table public.order_items add column if not exists reference_price numeric(10,2);

insert into public.promotions(title,description,promotion_type,status,starts_at,ends_at,product_ids,source,gift_product_id,gift_size_name)
select 'Primera compra Cande','Fresas Clásicas Chicas gratis en la primera compra válida','first_purchase_gift','active','2020-01-01', '2099-12-31',array['classic'],'system','classic','10 oz'
where not exists(select 1 from public.promotions where promotion_type='first_purchase_gift');

create or replace function private.first_purchase_offer_impl(p_customer_id uuid default auth.uid()) returns jsonb
language plpgsql security definer set search_path='' as $$declare p public.promotions;s public.product_sizes;eligible boolean;begin
 if p_customer_id is null or (p_customer_id<>auth.uid() and not private.is_admin()) then raise exception 'NOT_AUTHORIZED'; end if;
 select * into p from public.promotions where promotion_type='first_purchase_gift' and status='active' and starts_at<=now() and ends_at>=now() order by created_at limit 1;
 if not found then return jsonb_build_object('eligible',false); end if;
 select * into s from public.product_sizes where product_id=p.gift_product_id and name=p.gift_size_name and active;
 eligible:=s.id is not null and not exists(select 1 from public.orders o where o.customer_id=p_customer_id and (o.status='delivered' or o.payment_status='paid'))
  and not exists(select 1 from public.promotion_redemptions r where r.promotion_id=p.id and r.customer_id=p_customer_id and r.status in('reserved','used'));
 return jsonb_build_object('eligible',eligible,'promotionId',p.id,'productId',p.gift_product_id,'productName',(select name from public.products where id=p.gift_product_id),'sizeName',p.gift_size_name,'referencePrice',s.price);
end$$;
create or replace function public.first_purchase_offer() returns jsonb language sql security invoker set search_path='' as $$select private.first_purchase_offer_impl(auth.uid())$$;
revoke all on function public.first_purchase_offer(),private.first_purchase_offer_impl(uuid) from public,anon;
grant execute on function public.first_purchase_offer() to authenticated;

create or replace function private.place_order_impl(p_client_request_id uuid,p_items jsonb,p_delivery_type text,p_address jsonb,p_references text,p_notes text,p_payment_method text,p_redemption_ids uuid[])
returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=auth.uid();c public.customers;e public.orders;o public.orders;i jsonb;p public.products;s public.product_sizes;tops jsonb;tt numeric:=0;sub numeric:=0;ship numeric:=0;disc numeric:=0;line numeric;q int;quote jsonb;rate numeric:=0;mult numeric:=1;pending int:=0;rid uuid;rr public.reward_redemptions;rw public.rewards;hasfree boolean;promo public.promotions;promo_red uuid;gift jsonb;
begin
 if u is null then raise exception 'AUTH_REQUIRED';end if;if p_client_request_id is null then raise exception 'REQUEST_ID_REQUIRED';end if;
 if p_delivery_type not in('delivery','pickup') then raise exception 'INVALID_DELIVERY_TYPE';end if;if p_payment_method not in('Efectivo','Transferencia / SPEI') then raise exception 'INVALID_PAYMENT_METHOD';end if;
 if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'EMPTY_ORDER';end if;
 c:=private.ensure_customer_profile(u);select * into c from public.customers where id=u for update;
 select * into e from public.orders where client_request_id=p_client_request_id;if found then return jsonb_build_object('id',e.id,'orderNumber',e.order_number,'subtotal',e.subtotal,'deliveryFee',e.delivery_fee,'discount',e.discount,'total',e.total,'strawberriesPending',case when e.points_awarded_at is null then floor(e.total*.2) else e.points_earned end,'duplicate',true,'gift',exists(select 1 from public.order_items x where x.order_id=e.id and x.item_type='promotion_gift'));end if;
 for i in select value from jsonb_array_elements(p_items) loop if nullif(i->>'redemptionId','') is not null then continue;end if;q:=greatest(1,least(50,coalesce((i->>'quantity')::int,1)));select * into p from public.products where id=i->>'productId' and active and availability_status='active';if not found then raise exception 'PRODUCT_NOT_AVAILABLE';end if;select * into s from public.product_sizes where product_id=p.id and name=i->>'size' and active;if not found then raise exception 'SIZE_NOT_AVAILABLE';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'price',t.price) order by t.name),'[]') into tops from public.toppings t where t.active and(case when jsonb_array_length(coalesce(i->'toppingIds','[]'))>0 then t.id::text in(select jsonb_array_elements_text(i->'toppingIds')) else t.name in(select jsonb_array_elements_text(coalesce(i->'toppingNames','[]'))) end)and(not exists(select 1 from public.topping_products tp where tp.product_id=p.id)or exists(select 1 from public.topping_products tp where tp.product_id=p.id and tp.topping_id=t.id));select coalesce(sum((x->>'price')::numeric),0) into tt from jsonb_array_elements(tops)x;sub:=sub+(s.price+tt)*q;end loop;
 if p_delivery_type='delivery' then quote:=private.calculate_delivery_quote((p_address#>>'{coordinates,latitude}')::numeric,(p_address#>>'{coordinates,longitude}')::numeric,sub);if not coalesce((quote->>'serviceable')::boolean,false)then raise exception '%',coalesce(quote->>'reason','DELIVERY_NOT_AVAILABLE');end if;ship:=coalesce((quote->>'fee')::numeric,0);else quote:=jsonb_build_object('distanceKm',null,'driverPay',0,'businessShare',0,'method','pickup');end if;
 foreach rid in array coalesce(p_redemption_ids,'{}') loop select * into rr from public.reward_redemptions where id=rid and customer_id=u and status='available' for update;if not found then raise exception 'REDEMPTION_NOT_AVAILABLE';end if;select * into rw from public.rewards where id=rr.reward_id and active;if rw.reward_type='fixed_discount'then disc:=disc+least(coalesce(rw.reward_value,0),greatest(0,sub-disc));elsif rw.reward_type='free_product'then select exists(select 1 from jsonb_array_elements(p_items)x where x->>'redemptionId'=rr.id::text and x->>'productId'=rw.product_id and x->>'size'=rw.size_name)into hasfree;if not hasfree then raise exception 'FREE_REWARD_ITEM_MISSING';end if;end if;end loop;
 select * into promo from public.promotions where promotion_type='first_purchase_gift' and status='active' and starts_at<=now() and ends_at>=now() order by created_at limit 1;
 if promo.id is not null and not exists(select 1 from public.orders x where x.customer_id=u and(x.status='delivered'or x.payment_status='paid'))then insert into public.promotion_redemptions(promotion_id,customer_id)values(promo.id,u)on conflict do nothing returning id into promo_red;end if;
 insert into public.orders(client_request_id,customer_id,delivery_type,address,references_text,notes,payment_method,subtotal,delivery_fee,discount,total,delivery_distance_km,driver_pay,delivery_business_share,delivery_rate_snapshot,order_source,created_by)values(p_client_request_id,u,p_delivery_type,p_address,nullif(trim(p_references),''),nullif(trim(p_notes),''),p_payment_method,sub,ship,disc,greatest(0,sub+ship-disc),nullif(quote->>'distanceKm','')::numeric,coalesce((quote->>'driverPay')::numeric,0),coalesce((quote->>'businessShare')::numeric,0),quote,'app',u)returning * into o;
 for i in select value from jsonb_array_elements(p_items) loop
  if nullif(i->>'redemptionId','') is not null then select * into rr from public.reward_redemptions where id=(i->>'redemptionId')::uuid and customer_id=u and status='available' for update;select * into rw from public.rewards where id=rr.reward_id;select * into p from public.products where id=rw.product_id;select * into s from public.product_sizes where product_id=p.id and name=rw.size_name;insert into public.order_items(order_id,product_id,product_name,size_name,unit_price,quantity,toppings,line_total,item_type,reference_price)values(o.id,p.id,p.name,s.name,0,1,'[]',0,'reward',s.price);
  else q:=greatest(1,least(50,coalesce((i->>'quantity')::int,1)));select * into p from public.products where id=i->>'productId';select * into s from public.product_sizes where product_id=p.id and name=i->>'size';select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'price',t.price)order by t.name),'[]')into tops from public.toppings t where t.active and(case when jsonb_array_length(coalesce(i->'toppingIds','[]'))>0 then t.id::text in(select jsonb_array_elements_text(i->'toppingIds'))else t.name in(select jsonb_array_elements_text(coalesce(i->'toppingNames','[]')))end)and(not exists(select 1 from public.topping_products tp where tp.product_id=p.id)or exists(select 1 from public.topping_products tp where tp.product_id=p.id and tp.topping_id=t.id));select coalesce(sum((x->>'price')::numeric),0)into tt from jsonb_array_elements(tops)x;line:=(s.price+tt)*q;insert into public.order_items(order_id,product_id,product_name,size_name,unit_price,quantity,toppings,line_total,reference_price)values(o.id,p.id,p.name,s.name,s.price,q,tops,line,s.price);end if;end loop;
 if promo_red is not null then select * into p from public.products where id=promo.gift_product_id and active;select * into s from public.product_sizes where product_id=p.id and name=promo.gift_size_name and active;if p.id is not null and s.id is not null then insert into public.order_items(order_id,product_id,product_name,size_name,unit_price,quantity,toppings,line_total,item_type,promotion_id,reference_price)values(o.id,p.id,p.name,s.name,0,1,'[]',0,'promotion_gift',promo.id,s.price);update public.promotion_redemptions set order_id=o.id where id=promo_red;gift:=jsonb_build_object('productName',p.name,'sizeName',s.name,'referencePrice',s.price);else update public.promotion_redemptions set status='cancelled',cancelled_at=now()where id=promo_red;end if;end if;
 update public.reward_redemptions set status='used',order_id=o.id,used_at=now()where id=any(coalesce(p_redemption_ids,'{}'))and customer_id=u and status='available';select points_per_peso,multiplier into rate,mult from public.point_rules where active and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>=now())order by multiplier desc,points_per_peso desc limit 1;pending:=floor(o.total*coalesce(rate,0)*coalesce(mult,1));return jsonb_build_object('id',o.id,'orderNumber',o.order_number,'subtotal',o.subtotal,'deliveryFee',o.delivery_fee,'discount',o.discount,'total',o.total,'strawberriesPending',pending,'duplicate',false,'gift',gift);
end$$;

create or replace function private.admin_create_external_order_impl(p_request_id uuid,p_source text,p_customer_name text,p_phone text,p_items jsonb,p_address jsonb,p_references text,p_notes text,p_payment_method text,p_payment_status text,p_delivery_fee numeric,p_driver_pay numeric,p_apply_first_purchase boolean default false)returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid();cid uuid;eid uuid;o public.orders;i jsonb;p public.products;s public.product_sizes;tops jsonb;tt numeric;q int;sub numeric:=0;line numeric;norm text:=regexp_replace(coalesce(p_phone,''),'[^0-9]','','g');promo public.promotions;prid uuid;
begin if not private.is_admin()then raise exception 'ADMIN_REQUIRED';end if;if p_source not in('whatsapp','messenger','manual','other')then raise exception 'INVALID_ORDER_SOURCE';end if;if p_payment_method not in('Efectivo','Transferencia / SPEI')or p_payment_status not in('pending','paid')then raise exception 'INVALID_PAYMENT';end if;if jsonb_typeof(p_items)<>'array'or jsonb_array_length(p_items)=0 then raise exception 'EMPTY_ORDER';end if;
 select id into cid from public.customers where regexp_replace(phone,'[^0-9]','','g')=norm order by created_at limit 1;if cid is null then insert into public.external_contacts(name,phone,normalized_phone)values(trim(p_customer_name),trim(p_phone),norm)on conflict(normalized_phone)do update set name=excluded.name,phone=excluded.phone,updated_at=now()returning id into eid;else perform 1 from public.customers where id=cid for update;end if;
 for i in select value from jsonb_array_elements(p_items)loop q:=greatest(1,least(50,coalesce((i->>'quantity')::int,1)));select * into p from public.products where id=i->>'productId'and active and availability_status='active';if not found then raise exception 'PRODUCT_NOT_AVAILABLE';end if;select * into s from public.product_sizes where product_id=p.id and name=i->>'size'and active;if not found then raise exception 'SIZE_NOT_AVAILABLE';end if;select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'price',t.price)),'[]')into tops from public.toppings t where t.active and t.id::text in(select jsonb_array_elements_text(coalesce(i->'toppingIds','[]')));select coalesce(sum((x->>'price')::numeric),0)into tt from jsonb_array_elements(tops)x;sub:=sub+(s.price+tt)*q;end loop;
 insert into public.orders(client_request_id,customer_id,external_contact_id,status,delivery_type,address,references_text,notes,payment_method,payment_status,subtotal,delivery_fee,total,driver_pay,delivery_business_share,order_source,created_by)values(p_request_id,cid,eid,'ready','delivery',p_address,nullif(trim(p_references),''),nullif(trim(p_notes),''),p_payment_method,p_payment_status,sub,greatest(0,p_delivery_fee),sub+greatest(0,p_delivery_fee),greatest(0,p_driver_pay),greatest(0,p_delivery_fee-p_driver_pay),p_source,uid)returning * into o;
 for i in select value from jsonb_array_elements(p_items)loop q:=greatest(1,least(50,coalesce((i->>'quantity')::int,1)));select * into p from public.products where id=i->>'productId';select * into s from public.product_sizes where product_id=p.id and name=i->>'size';select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'price',t.price)),'[]')into tops from public.toppings t where t.active and t.id::text in(select jsonb_array_elements_text(coalesce(i->'toppingIds','[]')));select coalesce(sum((x->>'price')::numeric),0)into tt from jsonb_array_elements(tops)x;line:=(s.price+tt)*q;insert into public.order_items(order_id,product_id,product_name,size_name,unit_price,quantity,toppings,line_total,reference_price)values(o.id,p.id,p.name,s.name,s.price,q,tops,line,s.price);end loop;
 if p_apply_first_purchase and cid is not null and not exists(select 1 from public.orders x where x.customer_id=cid and x.id<>o.id and(x.status='delivered'or x.payment_status='paid'))then select * into promo from public.promotions where promotion_type='first_purchase_gift'and status='active'order by created_at limit 1;insert into public.promotion_redemptions(promotion_id,customer_id,order_id)values(promo.id,cid,o.id)on conflict do nothing returning id into prid;if prid is not null then select * into p from public.products where id=promo.gift_product_id;select * into s from public.product_sizes where product_id=p.id and name=promo.gift_size_name;insert into public.order_items(order_id,product_id,product_name,size_name,unit_price,quantity,toppings,line_total,item_type,promotion_id,reference_price)values(o.id,p.id,p.name,s.name,0,1,'[]',0,'promotion_gift',promo.id,s.price);end if;end if;
 insert into public.audit_events(actor_id,event_type,entity_type,entity_id,reason,new_value)values(uid,'external_order_created','order',o.id::text,p_source,jsonb_build_object('orderNumber',o.order_number,'source',p_source,'customerLinked',cid is not null));return jsonb_build_object('id',o.id,'orderNumber',o.order_number,'subtotal',o.subtotal,'deliveryFee',o.delivery_fee,'total',o.total,'customerLinked',cid is not null,'firstPurchaseGift',prid is not null);
end$$;
create or replace function public.admin_create_external_order(p_request_id uuid,p_source text,p_customer_name text,p_phone text,p_items jsonb,p_address jsonb,p_references text,p_notes text,p_payment_method text,p_payment_status text,p_delivery_fee numeric,p_driver_pay numeric,p_apply_first_purchase boolean default false)returns jsonb language sql security invoker set search_path='' as $$select private.admin_create_external_order_impl(p_request_id,p_source,p_customer_name,p_phone,p_items,p_address,p_references,p_notes,p_payment_method,p_payment_status,p_delivery_fee,p_driver_pay,p_apply_first_purchase)$$;
revoke all on function public.admin_create_external_order(uuid,text,text,text,jsonb,jsonb,text,text,text,text,numeric,numeric,boolean),private.admin_create_external_order_impl(uuid,text,text,text,jsonb,jsonb,text,text,text,text,numeric,numeric,boolean)from public,anon;
grant execute on function public.admin_create_external_order(uuid,text,text,text,jsonb,jsonb,text,text,text,text,numeric,numeric,boolean)to authenticated;

create or replace function private.award_order_strawberries() returns trigger language plpgsql security definer set search_path='' as $$declare rate numeric;mult numeric;pts int;bal int;begin
 if new.status='cancelled'or new.customer_id is null then return new;end if;if new.points_awarded_at is not null or exists(select 1 from public.points_transactions where order_id=new.id and type='earn')then return new;end if;if not(new.status='delivered'or new.payment_status='paid')then return new;end if;
 select points_per_peso,multiplier into rate,mult from public.point_rules where active and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>=now())order by multiplier desc,points_per_peso desc limit 1;pts:=floor(new.total*coalesce(rate,0)*coalesce(mult,1));update public.customers set points_balance=points_balance+pts,lifetime_points=lifetime_points+pts,updated_at=now()where id=new.customer_id returning points_balance into bal;new.points_earned:=pts;new.points_awarded_at:=now();insert into public.points_transactions(customer_id,order_id,type,points,balance_after,description)values(new.customer_id,new.id,'earn',pts,bal,'Fresas Cande por pedido CAN-'||lpad(new.order_number::text,6,'0'))on conflict(order_id,type)do nothing;update public.promotion_redemptions set status='used',used_at=now()where order_id=new.id and status='reserved';return new;end$$;

drop function if exists public.driver_available_requests();drop function if exists private.driver_available_requests_impl();
create function private.driver_available_requests_impl()returns table(id uuid,order_id uuid,pay numeric,pickup_address text,status text,order_number bigint,delivery_address text,maps_url text,distance_km numeric,order_items jsonb,customer_name text,customer_trust_score numeric,customer_trust_level text,customer_completed_orders integer,customer_last_delivery timestamptz,safety_level text,safety_signals jsonb,offer_round integer,dispatch_priority_score numeric)language sql security definer set search_path='' as $$
 select r.id,r.order_id,r.pay,r.pickup_address,r.status,o.order_number,case when o.delivery_distance_km is null then coalesce(o.address->>'zone','Zona por confirmar')else format('A %s km de Cande',round(o.delivery_distance_km,1))end,null::text,o.delivery_distance_km,coalesce((select jsonb_agg(jsonb_build_object('product_name',i.product_name,'size_name',i.size_name,'quantity',i.quantity,'item_type',i.item_type)order by i.id)from public.order_items i where i.order_id=o.id),'[]'),split_part(coalesce(cu.name,ec.name,'Cliente'),' ',1),coalesce(tp.trust_score,case when cu.id is null then 50 else 50 end),coalesce(tp.trust_level,'new'),coalesce(tp.orders_completed,0),tp.last_completed_at,r.safety_level,r.safety_signals,offer.round,offer.dispatch_priority_score
 from public.driver_offers offer join public.delivery_requests r on r.id=offer.request_id join public.orders o on o.id=r.order_id left join public.customers cu on cu.id=o.customer_id left join public.external_contacts ec on ec.id=o.external_contact_id join public.couriers c on c.id=offer.courier_id and c.user_id=auth.uid()and c.active and c.status='available' left join public.customer_trust_profiles tp on tp.customer_id=o.customer_id
 where private.is_driver()and r.status='requested'and offer.status='offered'and offer.offered_at<=now()and coalesce(offer.expires_at,now()+interval'1 minute')>now()and(select count(*)from public.delivery_assignments a where a.courier_id=c.id and a.status not in('delivered','cancelled'))<3 and not exists(select 1 from public.delivery_request_rejections x where x.request_id=r.id and x.courier_id=c.id)order by offer.dispatch_priority_score desc,r.requested_at$$;
create function public.driver_available_requests()returns table(id uuid,order_id uuid,pay numeric,pickup_address text,status text,order_number bigint,delivery_address text,maps_url text,distance_km numeric,order_items jsonb,customer_name text,customer_trust_score numeric,customer_trust_level text,customer_completed_orders integer,customer_last_delivery timestamptz,safety_level text,safety_signals jsonb,offer_round integer,dispatch_priority_score numeric)language sql security definer set search_path='' as $$select * from private.driver_available_requests_impl()$$;
revoke all on function public.driver_available_requests(),private.driver_available_requests_impl()from public,anon;grant execute on function public.driver_available_requests()to authenticated;
create or replace function private.driver_dashboard_impl()returns jsonb language plpgsql security definer set search_path='' as $$declare c public.couriers;assignments jsonb;m public.driver_metrics;r public.driver_rank_configs;nr public.driver_rank_configs;begin
 if not private.is_driver()then raise exception 'DRIVER_REQUIRED';end if;select * into c from public.couriers where user_id=auth.uid()and active;if not found then raise exception 'COURIER_NOT_FOUND';end if;select * into m from private.refresh_driver_metrics(c.id);select * into r from public.driver_rank_configs where id=m.rank_id;select * into nr from public.driver_rank_configs where active and sort_order>r.sort_order order by sort_order limit 1;
 select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'status',a.status,'delivery_fee',a.delivery_fee,'accepted_at',a.accepted_at,'updated_at',a.updated_at,'orders',jsonb_build_object('id',o.id,'order_number',o.order_number,'total',o.total,'address',o.address,'references_text',o.references_text,'notes',o.notes,'payment_method',o.payment_method,'customers',jsonb_build_object('name',coalesce(cu.name,ec.name),'phone',coalesce(cu.phone,ec.phone),'trust_level',coalesce(tp.trust_level,'new'),'trust_score',coalesce(tp.trust_score,50),'completed_orders',coalesce(tp.orders_completed,0),'last_completed_at',tp.last_completed_at),'order_items',coalesce((select jsonb_agg(jsonb_build_object('product_name',i.product_name,'size_name',i.size_name,'quantity',i.quantity,'item_type',i.item_type)order by i.id)from public.order_items i where i.order_id=o.id),'[]')))order by a.accepted_at desc),'[]')into assignments from public.delivery_assignments a join public.orders o on o.id=a.order_id left join public.customers cu on cu.id=o.customer_id left join public.external_contacts ec on ec.id=o.external_contact_id left join public.customer_trust_profiles tp on tp.customer_id=o.customer_id where a.courier_id=c.id;
 return to_jsonb(c)||jsonb_build_object('delivery_assignments',assignments,'reputation',to_jsonb(m)||jsonb_build_object('rank',to_jsonb(r),'next_rank',to_jsonb(nr)));end$$;

create or replace function private.admin_set_order_status_impl(p_order_id uuid,p_status public.order_status)returns public.orders language plpgsql security definer set search_path='' as $$declare v public.orders;begin if not private.is_admin()then raise exception 'ADMIN_REQUIRED';end if;select * into v from public.orders where id=p_order_id for update;if not found then raise exception 'ORDER_NOT_FOUND';end if;if p_status='cancelled' then update public.orders set status='cancelled'where id=p_order_id returning * into v;update public.promotion_redemptions set status='cancelled',cancelled_at=now()where order_id=p_order_id and status='reserved';return v;end if;if not((v.status='pending'and p_status='confirmed')or(v.status='confirmed'and p_status='preparing')or(v.status='preparing'and p_status='ready'))then raise exception 'INVALID_STATUS_TRANSITION';end if;update public.orders set status=p_status where id=p_order_id returning * into v;return v;end$$;

grant select on public.promotion_redemptions,public.external_contacts to authenticated;
grant insert,update,delete on public.promotion_redemptions,public.external_contacts to authenticated;
commit;
