'use client'
import {useCallback,useEffect,useState} from 'react'
import {Gift,Plus,Save,Settings2} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Product={id:string;name:string;product_sizes:{name:string;active:boolean}[]}
type Reward={id:string;name:string;description:string;points_cost:number;reward_type:'fixed_discount'|'free_product';reward_value:number|null;product_id:string|null;size_name:string|null;active:boolean;sort_order:number}
const emptyReward=():Reward=>({id:`new-${crypto.randomUUID()}`,name:'Nueva recompensa',description:'',points_cost:100,reward_type:'fixed_discount',reward_value:20,product_id:null,size_name:null,active:true,sort_order:10})

export default function AdminRewards(){
 const[rewards,setRewards]=useState<Reward[]>([]),[products,setProducts]=useState<Product[]>([]),[pesos,setPesos]=useState(5),[saving,setSaving]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{if(!supabase)return;const[r,p,rule]=await Promise.all([supabase.from('rewards').select('id,name,description,points_cost,reward_type,reward_value,product_id,size_name,active,sort_order').order('sort_order'),supabase.from('products').select('id,name,product_sizes(name,active)').order('name'),supabase.from('point_rules').select('points_per_peso').eq('active',true).order('starts_at',{ascending:false}).limit(1).maybeSingle()]);if(r.error||p.error||rule.error){setNotice('No pudimos cargar la configuración.');return}setRewards((r.data||[]) as Reward[]);setProducts((p.data||[]) as Product[]);setPesos(Number((1/Number(rule.data?.points_per_peso||.2)).toFixed(2)))},[])
 useEffect(()=>{load()},[load])
 function change(id:string,patch:Partial<Reward>){setRewards(v=>v.map(r=>r.id===id?{...r,...patch}:r))}
 async function saveRule(){if(!supabase||pesos<=0)return;if(!confirm(`Cambiar la equivalencia a $${pesos} MXN por cada Fresa Cande?`))return;setSaving('rule');setNotice('');const{error}=await supabase.rpc('admin_save_strawberry_rule',{p_pesos_per_strawberry:pesos});setSaving('');setNotice(error?`No se pudo guardar: ${error.message}`:'Cambios guardados correctamente.');if(!error)await load()}
 async function saveReward(reward:Reward){if(!supabase)return;if(!confirm(`Guardar cambios de “${reward.name}”?`))return;setSaving(reward.id);setNotice('');const{error}=await supabase.rpc('admin_save_reward',{p_data:{id:reward.id.startsWith('new-')?null:reward.id,name:reward.name,description:reward.description,points_cost:Number(reward.points_cost),reward_type:reward.reward_type,reward_value:reward.reward_type==='fixed_discount'?Number(reward.reward_value||0):null,product_id:reward.reward_type==='free_product'?reward.product_id:null,size_name:reward.reward_type==='free_product'?reward.size_name:null,active:reward.active,sort_order:Number(reward.sort_order)}});setSaving('');setNotice(error?`No se pudo guardar: ${error.message}`:'Cambios guardados correctamente.');if(!error)await load()}
 return <main className="mx-auto min-h-screen max-w-6xl bg-[#fffafb] px-4 pb-20 pt-24 sm:px-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-cande-500">Administrar tienda</p><h1 className="mt-1 text-3xl font-black">🍓 Fresas Cande</h1><p className="mt-2 max-w-xl text-sm text-zinc-500">Configura la acumulación y los premios. Los cálculos finales siempre se validan en Supabase.</p></div><button onClick={()=>setRewards(v=>[...v,emptyReward()])} className="flex h-12 items-center gap-2 rounded-full bg-cande-500 px-5 font-black text-white"><Plus size={18}/>Nueva recompensa</button></header>
  {notice&&<p role="status" className="mt-5 rounded-md border border-green-200 bg-green-50 p-4 font-bold text-green-800">{notice}</p>}
  <section className="card mt-6 p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-cande-100 text-cande-600"><Settings2/></span><div><h2 className="font-black">Regla de acumulación</h2><p className="text-sm text-zinc-500">Solo se acredita en pedidos pagados o entregados.</p></div></div><label className="mt-5 block text-xs font-black uppercase text-zinc-500">Pesos MXN por 1 🍓</label><div className="mt-2 flex gap-2"><input type="number" min="0.01" step="0.01" value={pesos} onChange={e=>setPesos(Number(e.target.value))} className="input max-w-xs"/><button disabled={saving==='rule'} onClick={saveRule} className="flex min-h-12 items-center gap-2 rounded-full bg-zinc-900 px-5 font-bold text-white"><Save size={17}/>Guardar regla</button></div><p className="mt-3 text-sm font-bold text-cande-700">Ejemplo: $100 generan {pesos>0?Math.floor(100/pesos):0} 🍓</p></section>
  <section className="mt-6 grid gap-4 lg:grid-cols-2">{rewards.map(reward=>{const product=products.find(p=>p.id===reward.product_id),sizes=product?.product_sizes.filter(s=>s.active)||[];return <article key={reward.id} className="card p-5"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-cande-100 text-cande-600"><Gift/></span><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={reward.active} onChange={e=>change(reward.id,{active:e.target.checked})} className="h-5 w-5 accent-cande-500"/>Activa</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Nombre"><input className="input" value={reward.name} onChange={e=>change(reward.id,{name:e.target.value})}/></Field><Field label="Fresas requeridas"><input type="number" min="1" className="input" value={reward.points_cost} onChange={e=>change(reward.id,{points_cost:Number(e.target.value)})}/></Field><div className="sm:col-span-2"><Field label="Descripción"><textarea className="input min-h-20" value={reward.description} onChange={e=>change(reward.id,{description:e.target.value})}/></Field></div><Field label="Tipo"><select className="input" value={reward.reward_type} onChange={e=>change(reward.id,{reward_type:e.target.value as Reward['reward_type']})}><option value="fixed_discount">Descuento</option><option value="free_product">Producto gratis</option></select></Field>{reward.reward_type==='fixed_discount'?<Field label="Valor del descuento MXN"><input type="number" min="0" className="input" value={reward.reward_value||0} onChange={e=>change(reward.id,{reward_value:Number(e.target.value)})}/></Field>:<><Field label="Producto gratis"><select className="input" value={reward.product_id||''} onChange={e=>change(reward.id,{product_id:e.target.value||null,size_name:null})}><option value="">Seleccionar</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Tamaño"><select className="input" value={reward.size_name||''} onChange={e=>change(reward.id,{size_name:e.target.value||null})}><option value="">Seleccionar</option>{sizes.map(s=><option key={s.name}>{s.name}</option>)}</select></Field></>}<Field label="Orden"><input type="number" className="input" value={reward.sort_order} onChange={e=>change(reward.id,{sort_order:Number(e.target.value)})}/></Field></div><button disabled={saving===reward.id} onClick={()=>saveReward(reward)} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white disabled:opacity-50"><Save size={18}/>{saving===reward.id?'Guardando…':'Guardar cambios'}</button></article>})}</section>
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-black uppercase text-zinc-500">{label}</span>{children}</label>}
