'use client'
import {useState} from 'react'
import Link from 'next/link'
import {Logo} from '@/components/logo'
import {useAuth} from '@/components/auth-provider'
import {supabase} from '@/lib/supabase'

const links=[['/admin','Dashboard'],['/admin/customers','Clientes'],['/admin/insights','Resumen'],['/admin/expansion','Expansión'],['/admin/store','Productos'],['/admin/inventory','Inventario'],['/admin/shipping','Tarifas'],['/admin/promotions','Promociones'],['/admin/rewards','Rewards'],['/admin/drivers','Equipo'],['/admin/delivery','Entregas'],['/admin/delivery/new','+ Pedido externo']]

export default function AdminLayout({children}:{children:React.ReactNode}){
 const{user,loading,refreshProfile,signOut}=useAuth(),[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),role=user?.app_metadata?.role
 async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{error:authError}=await supabase.auth.signInWithPassword({email:identifier.trim().toLowerCase(),password});setBusy(false);if(authError){setError('Credenciales incorrectas.');return}await refreshProfile()}
 if(loading)return <main className="grid min-h-screen place-items-center bg-cande-50"><p>Cargando…</p></main>
 if(!user)return <main className="grid min-h-screen place-items-center bg-cande-50 px-5"><section className="card w-full max-w-sm p-7"><Logo/><p className="mt-8 text-xs font-bold uppercase text-cande-500">Panel privado</p><h1 className="mt-1 text-2xl font-black">Acceso administrador</h1><p className="mt-2 text-sm text-zinc-500">Solo cuentas con el rol ADMIN pueden entrar.</p><form onSubmit={login} className="mt-6 space-y-3"><input required type="email" inputMode="email" className="input" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Correo electrónico" autoComplete="username"/><input required minLength={8} type="password" className="input" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Contraseña" autoComplete="current-password"/>{error&&<p className="text-sm font-bold text-red-700">{error}</p>}<button disabled={busy} className="h-12 w-full rounded-full bg-cande-500 font-bold text-white">{busy?'Entrando…':'Iniciar sesión'}</button></form><Link href="/" className="mt-5 block text-center text-sm font-bold text-zinc-500">Volver a la tienda</Link></section></main>
 if(role!=='ADMIN')return <main className="grid min-h-screen place-items-center bg-cande-50 px-5"><section className="card max-w-md p-7 text-center"><h1 className="text-2xl font-black">Acceso restringido</h1><p className="mt-2 text-sm text-zinc-500">Esta cuenta no tiene permisos de administrador.</p><button onClick={signOut} className="mt-5 rounded-full bg-cande-500 px-5 py-3 font-bold text-white">Cerrar sesión</button></section></main>
 return <><nav className="fixed inset-x-0 top-0 z-50 border-b bg-white/95 px-2 py-3 backdrop-blur"><div className="hide-scroll mx-auto flex max-w-7xl justify-end gap-1 overflow-x-auto">{links.map(([href,label],i)=><Link key={href} href={href} className={`rounded-full px-3 py-2 text-xs font-bold ${i===links.length-1?'bg-cande-500 text-white':'bg-cande-50 text-cande-700'}`}>{label}</Link>)}<button onClick={signOut} className="rounded-full px-3 py-2 text-xs font-bold text-zinc-500">Salir</button></div></nav>{children}</>
}
