'use client'
import {useEffect,useMemo,useState} from 'react'
import {BarChart3,DollarSign,Search,ShoppingBag,Star,Users} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'
type Customer={id:string;name:string;phone:string;points_balance:number;created_at:string;customer_levels:{name:string}|null}
type Order={id:string;customer_id:string;total:number;status:string;created_at:string;points_earned:number;order_items:{product_name:string;size_name:string;toppings:any}[]}
function Metric({label,value,Icon}:{label:string;value:string;Icon:any}){return <article className="card p-4"><span className="grid h-9 w-9 place-items-center rounded-md bg-cande-50 text-cande-600"><Icon size={18}/></span><p className="mt-4 text-2xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-zinc-500">{label}</p></article>}
export default function Admin(){const[customers,setCustomers]=useState<Customer[]>([]),[orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{if(!supabase)return;Promise.all([supabase.from('customers').select('id,name,phone,points_balance,created_at,customer_levels(name)').order('created_at',{ascending:false}),supabase.from('orders').select('id,customer_id,total,status,created_at,points_earned,order_items(product_name,size_name,toppings)').order('created_at',{ascending:false})]).then(([c,o])=>{setCustomers((c.data||[])as unknown as Customer[]);setOrders((o.data||[])as unknown as Order[]);setLoading(false)})},[])
 const data=useMemo(()=>{const now=new Date(),startDay=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),startWeek=startDay-((now.getDay()+6)%7)*86400000;const valid=orders.filter(o=>o.status!=='cancelled'),today=valid.filter(o=>new Date(o.created_at).getTime()>=startDay),week=valid.filter(o=>new Date(o.created_at).getTime()>=startWeek),sales=(rows:Order[])=>rows.reduce((n,o)=>n+Number(o.total),0),counts=new Map<string,number>();week.forEach(o=>o.order_items.forEach(i=>counts.set(i.product_name,(counts.get(i.product_name)||0)+1)));return{todaySales:sales(today),todayOrders:today.length,ticket:today.length?sales(today)/today.length:0,newCustomers:customers.filter(c=>new Date(c.created_at).getTime()>=startDay).length,weekSales:sales(week),weekOrders:week.length,points:week.reduce((n,o)=>n+o.points_earned,0),topProduct:[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sin ventas'}},[customers,orders]);const filtered=customers.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())||c.phone.includes(q));const byCustomer=new Map<string,Order[]>();orders.forEach(o=>byCustomer.set(o.customer_id,[...(byCustomer.get(o.customer_id)||[]),o]));
 return <main className="min-h-screen bg-[#fffafb] px-5 pb-24 pt-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase text-cande-500">Datos de Supabase</p><h1 className="mt-1 text-3xl font-black">Dashboard Cande</h1>{loading?<p className="mt-8 text-sm text-zinc-500">Cargando información real…</p>:<><section className="mt-8"><h2 className="section-title">Hoy</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Ventas" value={money(data.todaySales)} Icon={DollarSign}/><Metric label="Pedidos" value={String(data.todayOrders)} Icon={ShoppingBag}/><Metric label="Ticket promedio" value={money(data.ticket)} Icon={BarChart3}/><Metric label="Clientes nuevos" value={String(data.newCustomers)} Icon={Users}/><Metric label="Producto líder semanal" value={data.topProduct} Icon={Star}/></div></section><section className="card mt-8 p-5"><h2 className="section-title">Esta semana</h2><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><strong className="text-xl">{money(data.weekSales)}</strong><p className="text-xs text-zinc-500">Ventas</p></div><div><strong className="text-xl">{data.weekOrders}</strong><p className="text-xs text-zinc-500">Pedidos</p></div><div><strong className="text-xl">{data.points}</strong><p className="text-xs text-zinc-500">Puntos</p></div></div></section><section className="mt-9"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">Clientes</h2><label className="flex items-center gap-2 rounded-full border bg-white px-4 py-2"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente" className="w-40 outline-none"/></label></div><div className="mt-4 overflow-x-auto rounded-lg border border-cande-100 bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-cande-50 text-xs uppercase text-zinc-500"><tr>{['Nombre','Teléfono','Compras','Total gastado','Última compra','Puntos','Nivel'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{filtered.map(c=>{const own=byCustomer.get(c.id)||[],total=own.filter(o=>o.status!=='cancelled').reduce((n,o)=>n+Number(o.total),0);return <tr key={c.id} className="border-t border-cande-50"><td className="px-4 py-4 font-bold">{c.name}</td><td className="px-4 text-zinc-500">{c.phone}</td><td className="px-4">{own.length}</td><td className="px-4 font-bold">{money(total)}</td><td className="px-4">{own[0]?new Date(own[0].created_at).toLocaleDateString('es-MX'):'—'}</td><td className="px-4">{c.points_balance}</td><td className="px-4">{c.customer_levels?.name||'Fresa'}</td></tr>})}</tbody></table></div></section></>}</div></main>}
