'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { BarChart3, CalendarDays, DollarSign, Search, ShoppingBag, Star, Users } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { money } from '@/lib/data'

type Customer = { id:string; name:string; phone:string; points_balance:number; created_at:string; customer_levels:{name:string}|{name:string}[]|null }
type Order = { id:string; customer_id:string|null; total:number; discount:number; status:string; created_at:string; points_earned:number; order_items:{product_name:string;size_name:string;toppings:unknown;quantity:number}[] }
type RangeKey = 'today'|'yesterday'|'last7'|'thisWeek'|'lastWeek'|'thisMonth'|'lastMonth'|'custom'
type Period = { start:Date; end:Date; label:string }

const presets:{value:RangeKey;label:string}[]=[
  {value:'today',label:'Hoy'},{value:'yesterday',label:'Ayer'},{value:'last7',label:'Últimos 7 días'},
  {value:'thisWeek',label:'Esta semana'},{value:'lastWeek',label:'Semana anterior'},{value:'thisMonth',label:'Este mes'},
  {value:'lastMonth',label:'Mes anterior'},{value:'custom',label:'Rango personalizado'},
]

function dayStart(value:Date){const date=new Date(value);date.setHours(0,0,0,0);return date}
function dayEnd(value:Date){const date=dayStart(value);date.setDate(date.getDate()+1);return date}
function inputDate(value:Date){return value.toISOString().slice(0,10)}
function levelName(level:Customer['customer_levels']){return Array.isArray(level)?level[0]?.name||'Fresa':level?.name||'Fresa'}
function periodFor(range:RangeKey,customStart:string,customEnd:string,now=new Date()):Period{
 const today=dayStart(now),tomorrow=dayEnd(now),weekStart=new Date(today);weekStart.setDate(today.getDate()-((today.getDay()+6)%7))
 if(range==='today')return{start:today,end:tomorrow,label:'Hoy'}
 if(range==='yesterday'){const start=new Date(today);start.setDate(start.getDate()-1);return{start,end:today,label:'Ayer'}}
 if(range==='last7'){const start=new Date(today);start.setDate(start.getDate()-6);return{start,end:tomorrow,label:'Últimos 7 días'}}
 if(range==='thisWeek')return{start:weekStart,end:tomorrow,label:'Esta semana'}
 if(range==='lastWeek'){const end=weekStart,start=new Date(end);start.setDate(end.getDate()-7);return{start,end,label:'Semana anterior'}}
 if(range==='thisMonth')return{start:new Date(today.getFullYear(),today.getMonth(),1),end:tomorrow,label:'Este mes'}
 if(range==='lastMonth')return{start:new Date(today.getFullYear(),today.getMonth()-1,1),end:new Date(today.getFullYear(),today.getMonth(),1),label:'Mes anterior'}
 const start=customStart?dayStart(new Date(`${customStart}T00:00:00`)):new Date(0),end=customEnd?dayEnd(new Date(`${customEnd}T00:00:00`)):tomorrow
 return{start,end:end>start?end:dayEnd(start),label:'Rango personalizado'}
}

function Metric({label,value,Icon}:{label:string;value:string;Icon:typeof DollarSign}){return <article className="card p-4"><span className="grid h-9 w-9 place-items-center rounded-md bg-cande-50 text-cande-600"><Icon size={18}/></span><p className="mt-4 truncate text-2xl font-black" title={value}>{value}</p><p className="mt-1 text-xs font-bold text-zinc-500">{label}</p></article>}

export default function Admin(){
 const[customers,setCustomers]=useState<Customer[]>([]),[orders,setOrders]=useState<Order[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const[range,setRange]=useState<RangeKey>('today'),[customStart,setCustomStart]=useState(''),[customEnd,setCustomEnd]=useState('')
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError('');const[c,o]=await Promise.all([
  supabase.from('customers').select('id,name,phone,points_balance,created_at,customer_levels(name)').order('created_at',{ascending:false}),
  supabase.from('orders').select('id,customer_id,total,discount,status,created_at,points_earned,order_items(product_name,size_name,toppings,quantity)').order('created_at',{ascending:false}),
 ]);if(c.error||o.error){console.error('admin dashboard load failed',{customersCode:c.error?.code,ordersCode:o.error?.code});setError('No pudimos cargar las métricas. Intenta actualizar la pantalla.')}else{setCustomers((c.data||[])as Customer[]);setOrders((o.data||[])as Order[])}setLoading(false)},[])
 useEffect(()=>{load();if(!supabase)return;const channel=supabase.channel('admin-dashboard-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'customers'},load).subscribe();return()=>{supabase?.removeChannel(channel)}},[load])
 const period=useMemo(()=>periodFor(range,customStart,customEnd),[range,customStart,customEnd])
 const data=useMemo(()=>{const valid=orders.filter(order=>order.status!=='cancelled'),inPeriod=valid.filter(order=>{const date=new Date(order.created_at);return date>=period.start&&date<period.end}),sales=inPeriod.reduce((sum,order)=>sum+Number(order.total),0),firstOrder=new Map<string,Order>();[...valid].sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()).forEach(order=>{if(order.customer_id&&!firstOrder.has(order.customer_id))firstOrder.set(order.customer_id,order)});const newCustomers=[...firstOrder.values()].filter(order=>{const date=new Date(order.created_at);return date>=period.start&&date<period.end}).length,customerIds=new Set(inPeriod.map(order=>order.customer_id).filter((id):id is string=>Boolean(id))),recurrentCustomers=[...customerIds].filter(id=>{const first=firstOrder.get(id);return first?new Date(first.created_at)<period.start:false}).length,productCounts=new Map<string,number>();inPeriod.forEach(order=>order.order_items.forEach(item=>productCounts.set(item.product_name,(productCounts.get(item.product_name)||0)+Number(item.quantity||1))));const leader=[...productCounts.entries()].sort((a,b)=>b[1]-a[1])[0],discounts=inPeriod.reduce((sum,order)=>sum+Number(order.discount||0),0);return{orders:inPeriod,sales,ticket:inPeriod.length?sales/inPeriod.length:0,newCustomers,recurrentCustomers,units:[...productCounts.values()].reduce((sum,count)=>sum+count,0),discounts,leader:leader?.[0]||'Sin ventas',leaderUnits:leader?.[1]||0}},[orders,period])
 const filtered=customers.filter(customer=>customer.name.toLocaleLowerCase('es-MX').includes(query.toLocaleLowerCase('es-MX'))||customer.phone.includes(query)),byCustomer=useMemo(()=>{const map=new Map<string,Order[]>();orders.forEach(order=>{if(order.customer_id)map.set(order.customer_id,[...(map.get(order.customer_id)||[]),order])});return map},[orders])
 return <main className="min-h-screen bg-[#fffafb] px-5 pb-24 pt-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase text-cande-500">Datos de Supabase</p><h1 className="mt-1 text-3xl font-black">Dashboard Cande</h1>
 <section className="card mt-6 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><CalendarDays className="text-cande-600" size={19}/><strong className="text-sm">Periodo: {period.label}</strong></div><button type="button" onClick={load} className="rounded-full border border-cande-200 px-4 py-2 text-xs font-bold text-cande-700">Actualizar</button></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{presets.map(preset=><button key={preset.value} type="button" onClick={()=>setRange(preset.value)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${range===preset.value?'bg-cande-500 text-white':'bg-cande-50 text-cande-700'}`}>{preset.label}</button>)}</div>{range==='custom'&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="label">Desde</span><input className="input" type="date" max={customEnd||inputDate(new Date())} value={customStart} onChange={event=>setCustomStart(event.target.value)}/></label><label><span className="label">Hasta</span><input className="input" type="date" min={customStart} max={inputDate(new Date())} value={customEnd} onChange={event=>setCustomEnd(event.target.value)}/></label></div>}</section>
 {error&&<p role="alert" className="mt-5 rounded-md bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}{loading?<section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Cargando métricas" aria-busy="true">{[0,1,2,3].map(item=><div className="card space-y-3 p-4" key={item}><div className="skeleton h-9 w-9"/><div className="skeleton h-7 w-3/4"/><div className="skeleton h-4 w-2/3"/></div>)}</section>:<><section className="mt-8"><h2 className="section-title">Resumen de {period.label.toLocaleLowerCase('es-MX')}</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Ventas" value={money(data.sales)} Icon={DollarSign}/><Metric label="Pedidos" value={String(data.orders.length)} Icon={ShoppingBag}/><Metric label="Ticket promedio" value={money(data.ticket)} Icon={BarChart3}/><Metric label="Nuevos por primera compra" value={String(data.newCustomers)} Icon={Users}/><Metric label="Clientes recurrentes" value={String(data.recurrentCustomers)} Icon={Users}/><Metric label="Unidades vendidas" value={String(data.units)} Icon={ShoppingBag}/><Metric label="Descuentos otorgados" value={money(data.discounts)} Icon={DollarSign}/><Metric label="Producto líder" value={data.leader} Icon={Star}/></div></section>
 <section className="card mt-8 p-5"><h2 className="section-title">Lectura del periodo</h2><div className="mt-5 grid grid-cols-2 gap-4 text-center sm:grid-cols-4"><div><strong className="text-xl">{data.leaderUnits}</strong><p className="text-xs text-zinc-500">Unidades del líder</p></div><div><strong className="text-xl">{customers.length}</strong><p className="text-xs text-zinc-500">Clientes registrados</p></div><div><strong className="text-xl">{data.orders.filter(order=>order.status==='delivered').length}</strong><p className="text-xs text-zinc-500">Entregados</p></div><div><strong className="text-xl">{data.orders.filter(order=>order.status!=='delivered').length}</strong><p className="text-xs text-zinc-500">En proceso</p></div></div></section>
 <section className="mt-9"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">Clientes</h2><label className="flex items-center gap-2 rounded-full border bg-white px-4 py-2"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar cliente" aria-label="Buscar cliente" className="w-40 outline-none"/></label></div><div className="mt-4 overflow-x-auto rounded-lg border border-cande-100 bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-cande-50 text-xs uppercase text-zinc-500"><tr>{['Nombre','Teléfono','Compras','Total gastado','Última compra','Puntos','Nivel'].map(heading=><th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody>{filtered.map(customer=>{const own=(byCustomer.get(customer.id)||[]).filter(order=>order.status!=='cancelled'),total=own.reduce((sum,order)=>sum+Number(order.total),0);return <tr key={customer.id} className="border-t border-cande-50"><td className="px-4 py-4 font-bold">{customer.name}</td><td className="px-4 text-zinc-500">{customer.phone}</td><td className="px-4">{own.length}</td><td className="px-4 font-bold">{money(total)}</td><td className="px-4">{own[0]?new Date(own[0].created_at).toLocaleDateString('es-MX'):'—'}</td><td className="px-4">{customer.points_balance}</td><td className="px-4">{levelName(customer.customer_levels)}</td></tr>})}</tbody></table>{!filtered.length&&<p className="p-6 text-center text-sm text-zinc-500">No encontramos clientes con esa búsqueda.</p>}</div></section></>}</div></main>
}
