'use client'
import Image from 'next/image'
import Link from 'next/link'
import {useState} from 'react'
import {Minus,Plus,ShoppingBag,SlidersHorizontal} from 'lucide-react'
import {sizes,money} from '@/lib/data'
import {useCart} from '@/components/cart-provider'
import {ManagedProduct,ManagedTopping,useStore} from '@/components/store-provider'
import {Logo} from '@/components/logo'

function ProductCard({product,toppings}:{product:ManagedProduct;toppings:ManagedTopping[]}){
 const offered=sizes.filter(s=>product.availableSizes[s]),[size,setSize]=useState(offered[0]||'10 oz'),[selected,setSelected]=useState<string[]>([]),[qty,setQty]=useState(1),{add}=useCart()
 const available=toppings.filter(t=>t.active&&(!product.toppingIds.length||product.toppingIds.includes(t.id))),chosen=available.filter(t=>selected.includes(t.name)),unit=Number(product.prices[size])+chosen.reduce((n,t)=>n+Number(t.price),0),from=offered.length?Math.min(...offered.map(s=>Number(product.prices[s]))):0
 return <article className="card overflow-hidden"><div className="relative aspect-[16/10]"><Image src={product.image} alt={product.name} fill className="object-cover" unoptimized/>{product.specialty&&<span className="pill absolute left-3 top-3 bg-white px-3 py-1 text-xs font-bold text-cande-600 shadow">Especialidad</span>}</div><div className="p-5"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-cande-500">{product.category}</p><h2 className="text-xl font-black">{product.name}</h2><p className="mt-1 text-sm text-zinc-500">{product.description}</p></div><strong className="text-cande-700">{money(from)}+</strong></div><p className="mt-5 text-xs font-bold uppercase text-zinc-500">Elige tamaño</p><div className="mt-2 grid grid-cols-4 gap-2">{offered.map(s=><button onClick={()=>setSize(s)} className={`rounded-md border py-2 text-xs font-bold ${size===s?'border-cande-500 bg-cande-50 text-cande-700':'border-zinc-200'}`} key={s}>{s}</button>)}</div><p className="mt-5 text-xs font-bold uppercase text-zinc-500">Toppings</p><div className="mt-2 flex flex-wrap gap-2">{available.map(t=>{const active=selected.includes(t.name);return <button key={t.id} onClick={()=>setSelected(v=>active?v.filter(x=>x!==t.name):[...v,t.name])} className={`rounded-full border px-3 py-2 text-xs ${active?'border-cande-500 bg-cande-500 font-bold text-white':'border-zinc-200 text-zinc-600'}`}>{t.name} +{money(t.price)}</button>})}</div><div className="mt-5 flex items-center gap-3"><div className="flex h-12 items-center rounded-full border"><button aria-label="Disminuir" onClick={()=>setQty(Math.max(1,qty-1))} className="grid h-12 w-10 place-items-center"><Minus size={16}/></button><strong className="w-6 text-center">{qty}</strong><button aria-label="Aumentar" onClick={()=>setQty(qty+1)} className="grid h-12 w-10 place-items-center"><Plus size={16}/></button></div><button disabled={!offered.length} onClick={()=>add({productId:product.id,name:product.name,image:product.image,size,toppings:chosen,quantity:qty,unitPrice:unit})} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-full bg-cande-500 px-4 text-sm font-bold text-white disabled:opacity-50"><ShoppingBag size={18}/>Agregar · {money(unit*qty)}</button></div></div></article>
}
export default function Menu(){const{count,subtotal}=useCart(),{config,loading}=useStore(),products=config.products.filter(p=>p.availability==='active'&&p.active).sort((a,b)=>a.sortOrder-b.sortOrder);return <main className="page"><header className="flex items-center justify-between"><Logo/><SlidersHorizontal className="text-cande-700"/></header><div className="mt-8"><p className="text-xs font-bold uppercase text-cande-500">Fresas para hoy</p><h1 className="mt-1 text-3xl font-black">Elige tu favorita</h1><p className="mt-2 text-sm text-zinc-500">Personalízala a tu gusto. La preparamos al confirmar.</p></div>{loading?<p className="mt-8 text-center text-sm text-zinc-500">Cargando menú…</p>:<div className="mt-6 grid gap-5 md:grid-cols-2">{products.map(p=><ProductCard key={p.id} product={p} toppings={config.toppings}/>)}</div>}{count>0&&<Link href="/cart" className="fixed bottom-[138px] right-4 z-40 flex items-center gap-3 rounded-full bg-cande-900 px-5 py-3 text-sm font-bold text-white shadow-xl"><ShoppingBag size={18}/>{count} · {money(subtotal)}</Link>}</main>}
