'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {Crown,Gift,Lock,Sparkles,Ticket,TrendingUp} from 'lucide-react'
import {useAuth} from '@/components/auth-provider'
import {supabase} from '@/lib/supabase'
type Reward={id:string;name:string;description:string;points_cost:number;reward_type:string}
const icons=[Sparkles,Ticket,Gift,Crown]
export default function Rewards(){const{user,profile,loading,refreshProfile}=useAuth();const[rewards,setRewards]=useState<Reward[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState('')
 useEffect(()=>{if(!supabase)return;supabase.from('rewards').select('id,name,description,points_cost,reward_type').order('sort_order').then(({data})=>setRewards((data||[])as Reward[]))},[])
 async function redeem(id:string){if(!supabase)return;setBusy(id);setNotice('');const{data,error}=await supabase.rpc('redeem_reward',{p_reward_id:id});setBusy('');if(error){setNotice(error.message.includes('INSUFFICIENT')?'No tienes puntos suficientes.':'No pudimos completar el canje.');return}await refreshProfile();setNotice(`Canje realizado. Tu nuevo saldo es ${(data as any).balance} puntos.`)}
 if(loading)return <main className="page"><p className="text-center text-sm text-zinc-500">Cargando Rewards…</p></main>
 const points=profile?.points_balance||0,level=profile?.customer_levels?.name||'Fresa'
 return <main className="page max-w-4xl"><header><p className="text-xs font-bold uppercase text-cande-500">Cande Rewards</p><h1 className="mt-1 text-3xl font-black">Cada antojo cuenta</h1><p className="mt-2 text-sm text-zinc-500">Tus puntos se guardan en tu cuenta Cande.</p></header>{!user?<section className="card mt-7 p-6 text-center"><h2 className="text-xl font-black">Inicia sesión para acumular</h2><p className="mt-2 text-sm text-zinc-500">Conserva tus puntos aunque cambies de celular.</p><Link href="/account?next=/rewards" className="mt-5 inline-flex rounded-full bg-cande-500 px-6 py-3 font-bold text-white">Entrar o registrarme</Link></section>:<section className="mt-7 overflow-hidden rounded-lg bg-cande-900 p-6 text-white md:p-8"><p className="text-xs font-bold uppercase text-cande-200">Saldo disponible</p><p className="mt-2 text-4xl font-black">{points} <span className="text-base">puntos</span></p><p className="mt-4 text-sm text-white/70">Nivel {level}</p></section>}{notice&&<p role="status" className="mt-4 rounded-md bg-cande-50 p-4 text-sm font-bold text-cande-800">{notice}</p>}<div className="mt-8 flex items-end justify-between"><h2 className="section-title">Recompensas</h2><span className="text-xs font-bold text-zinc-500">Configuradas en Supabase</span></div><section className="mt-4 grid gap-3 sm:grid-cols-2">{rewards.map((r,i)=>{const Icon=icons[i%icons.length],ready=Boolean(user)&&points>=r.points_cost;return <article key={r.id} className="card flex items-center gap-4 p-4"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-full ${ready?'bg-cande-100 text-cande-600':'bg-zinc-100 text-zinc-400'}`}><Icon size={21}/></span><div className="min-w-0 flex-1"><h3 className="font-extrabold">{r.name}</h3><p className="text-sm font-bold text-cande-600">{r.points_cost} pts</p></div>{ready?<button disabled={busy===r.id} onClick={()=>redeem(r.id)} className="rounded-full bg-cande-500 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{busy===r.id?'…':'Canjear'}</button>:<Lock size={17} className="text-zinc-400"/>}</article>})}</section>{user&&<section className="mt-10"><h2 className="section-title">Tu nivel</h2><div className="card mt-4 flex items-center gap-3 p-6"><TrendingUp className="text-cande-600"/><div><strong>Nivel {level}</strong><p className="text-xs text-zinc-500">Puntos históricos: {profile?.lifetime_points||0}</p></div></div></section>}</main>}
