'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { LocateFixed, Plus, Save, Trash2, Truck } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { money } from '@/lib/data'

type Settings = { enabled:boolean;storeLatitude:string;storeLongitude:string;routeFactor:number;maxDistanceKm:number;additionalFeePerKm:number;driverMinPay:number;driverBasePay:number;driverAdditionalPerKm:number;freeShippingEnabled:boolean;freeShippingMinOrder:number;freeShippingMaxKm:number }
type Tier = { id?:string;maxKm:number;fee:number }
type Order = { delivery_fee:number;driver_pay:number;delivery_business_share:number;delivery_distance_km:number|null;address:any }
const initial:Settings={enabled:false,storeLatitude:'',storeLongitude:'',routeFactor:1.2,maxDistanceKm:6,additionalFeePerKm:12,driverMinPay:25,driverBasePay:20,driverAdditionalPerKm:3,freeShippingEnabled:false,freeShippingMinOrder:0,freeShippingMaxKm:0}

export default function ShippingAdmin(){
 const[settings,setSettings]=useState(initial),[tiers,setTiers]=useState<Tier[]>([]),[orders,setOrders]=useState<Order[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{if(!supabase)return;const[s,t,o]=await Promise.all([supabase.from('delivery_rate_settings').select('*').eq('id','main').single(),supabase.from('delivery_rate_tiers').select('*').order('max_km'),supabase.from('orders').select('delivery_fee,driver_pay,delivery_business_share,delivery_distance_km,address').eq('delivery_type','delivery')]);if(s.data)setSettings({enabled:s.data.enabled,storeLatitude:s.data.store_latitude===null?'':String(s.data.store_latitude),storeLongitude:s.data.store_longitude===null?'':String(s.data.store_longitude),routeFactor:Number(s.data.route_factor),maxDistanceKm:Number(s.data.max_distance_km),additionalFeePerKm:Number(s.data.additional_fee_per_km),driverMinPay:Number(s.data.driver_min_pay),driverBasePay:Number(s.data.driver_base_pay),driverAdditionalPerKm:Number(s.data.driver_additional_per_km),freeShippingEnabled:s.data.free_shipping_enabled,freeShippingMinOrder:Number(s.data.free_shipping_min_order),freeShippingMaxKm:Number(s.data.free_shipping_max_km)});setTiers((t.data||[]).map((x:any)=>({id:x.id,maxKm:Number(x.max_km),fee:Number(x.fee)})));setOrders((o.data||[]) as Order[])},[])
 useEffect(()=>{load()},[load])
 const report=useMemo(()=>{const measured=orders.filter(o=>o.delivery_distance_km!==null),sum=(key:keyof Order)=>orders.reduce((n,o)=>n+Number(o[key]||0),0);return{income:sum('delivery_fee'),driver:sum('driver_pay'),business:sum('delivery_business_share'),average:measured.length?measured.reduce((n,o)=>n+Number(o.delivery_distance_km),0)/measured.length:0,averageFee:orders.length?sum('delivery_fee')/orders.length:0}},[orders])
 function locate(){navigator.geolocation?.getCurrentPosition(({coords})=>setSettings(s=>({...s,storeLatitude:coords.latitude.toFixed(7),storeLongitude:coords.longitude.toFixed(7)})),()=>setNotice('No pudimos obtener la ubicación. Revisa el permiso del navegador.'),{enableHighAccuracy:true,timeout:12000})}
 async function save(e:FormEvent){e.preventDefault();if(!supabase||!confirm('¿Guardar y aplicar este tabulador de envío?'))return;if(settings.enabled&&(!settings.storeLatitude||!settings.storeLongitude)){setNotice('Comparte primero la ubicación real del negocio.');return}setBusy(true);const{error}=await supabase.rpc('admin_save_delivery_rates',{p_settings:settings,p_tiers:tiers.sort((a,b)=>a.maxKm-b.maxKm).map(t=>({maxKm:Number(t.maxKm),fee:Number(t.fee)}))});setBusy(false);setNotice(error?error.message:'Tarifas guardadas correctamente. Los pedidos nuevos usarán este tabulador.');if(!error)await load()}
 const patch=(value:Partial<Settings>)=>setSettings(s=>({...s,...value}))
 return <main className="mx-auto min-h-screen max-w-6xl bg-[#fffafb] px-4 pb-20 pt-24"><header><p className="text-xs font-black uppercase text-cande-500">Configuración logística</p><h1 className="mt-1 text-3xl font-black">🚚 Tarifas de envío</h1><p className="mt-2 text-sm text-zinc-500">Distancia aproximada de trayecto calculada de forma segura en Supabase.</p></header>{notice&&<button onClick={()=>setNotice('')} className="mt-5 w-full rounded-md bg-green-50 p-4 text-left font-bold text-green-800">{notice}</button>}
 <form onSubmit={save} className="mt-6 space-y-6"><section className="card p-5"><label className="flex items-center justify-between gap-4"><span><strong className="block">Cobro por distancia</strong><small className="text-zinc-500">Actívalo después de guardar la ubicación del negocio.</small></span><input type="checkbox" checked={settings.enabled} onChange={e=>patch({enabled:e.target.checked})} className="h-6 w-6 accent-cande-500"/></label><button type="button" onClick={locate} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white"><LocateFixed size={18}/>USAR UBICACIÓN ACTUAL DEL NEGOCIO</button><div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="Latitud del negocio" value={settings.storeLatitude} set={v=>patch({storeLatitude:v})}/><NumberField label="Longitud del negocio" value={settings.storeLongitude} set={v=>patch({storeLongitude:v})}/><NumberField label="Factor aproximado de ruta" value={settings.routeFactor} set={v=>patch({routeFactor:Number(v)})}/><NumberField label="Distancia máxima (km)" value={settings.maxDistanceKm} set={v=>patch({maxDistanceKm:Number(v)})}/><NumberField label="Adicional por km después del último rango" value={settings.additionalFeePerKm} set={v=>patch({additionalFeePerKm:Number(v)})}/></div></section>
 <section className="card p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Tabulador</h2><button type="button" onClick={()=>setTiers(t=>[...t,{maxKm:(t.at(-1)?.maxKm||0)+1,fee:(t.at(-1)?.fee||0)+10}])} className="flex items-center gap-1 rounded-full bg-cande-50 px-4 py-2 text-sm font-black text-cande-700"><Plus size={16}/>Rango</button></div><div className="mt-4 space-y-3">{tiers.map((tier,index)=><div key={tier.id||index} className="grid grid-cols-[1fr_1fr_44px] gap-2"><label><span className="label">Hasta km</span><input type="number" step=".1" min=".1" className="input" value={tier.maxKm} onChange={e=>setTiers(v=>v.map((x,i)=>i===index?{...x,maxKm:Number(e.target.value)}:x))}/></label><label><span className="label">Cobro</span><input type="number" min="0" className="input" value={tier.fee} onChange={e=>setTiers(v=>v.map((x,i)=>i===index?{...x,fee:Number(e.target.value)}:x))}/></label><button type="button" aria-label="Eliminar rango" onClick={()=>setTiers(v=>v.filter((_,i)=>i!==index))} className="mt-6 grid h-11 place-items-center text-red-600"><Trash2 size={18}/></button></div>)}</div></section>
 <section className="card p-5"><h2 className="text-xl font-black">Pago al repartidor</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><NumberField label="Pago mínimo" value={settings.driverMinPay} set={v=>patch({driverMinPay:Number(v)})}/><NumberField label="Pago base" value={settings.driverBasePay} set={v=>patch({driverBasePay:Number(v)})}/><NumberField label="Adicional por km" value={settings.driverAdditionalPerKm} set={v=>patch({driverAdditionalPerKm:Number(v)})}/></div></section>
 <section className="card p-5"><label className="flex items-center justify-between"><strong>Envío gratis configurable</strong><input type="checkbox" checked={settings.freeShippingEnabled} onChange={e=>patch({freeShippingEnabled:e.target.checked})} className="h-6 w-6 accent-cande-500"/></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="Compra mínima" value={settings.freeShippingMinOrder} set={v=>patch({freeShippingMinOrder:Number(v)})}/><NumberField label="Dentro de km" value={settings.freeShippingMaxKm} set={v=>patch({freeShippingMaxKm:Number(v)})}/></div></section>
 <button disabled={busy||!tiers.length} className="flex h-14 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white disabled:opacity-50"><Save size={19}/>{busy?'Guardando…':'GUARDAR Y APLICAR'}</button></form>
 <section className="mt-9"><h2 className="text-xl font-black">Reporte de envíos</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5"><Metric label="Ingresos" value={money(report.income)}/><Metric label="Pago repartidores" value={money(report.driver)}/><Metric label="Conserva negocio" value={money(report.business)}/><Metric label="Distancia promedio" value={`${report.average.toFixed(1)} km`}/><Metric label="Envío promedio" value={money(report.averageFee)}/></div></section></main>
}
function NumberField({label,value,set}:{label:string;value:string|number;set:(v:string)=>void}){return <label><span className="label">{label}</span><input required type="number" step="any" className="input" value={value} onChange={e=>set(e.target.value)}/></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="card p-4 text-center"><Truck className="mx-auto text-cande-500" size={18}/><strong className="mt-2 block">{value}</strong><span className="text-[10px] text-zinc-500">{label}</span></div>}
