'use client'
import Link from 'next/link'
import {FormEvent,useMemo,useState} from 'react'
import {ArrowLeft,Plus,Trash2} from 'lucide-react'
import {useStore} from '@/components/store-provider'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'

type Line={id:string;productId:string;size:string;quantity:number;toppingIds:string[]}
const fresh=():Line=>({id:crypto.randomUUID(),productId:'',size:'',quantity:1,toppingIds:[]})
export default function NewExternalOrder(){const{config}=useStore();const[lines,setLines]=useState<Line[]>([]),[name,setName]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[references,setReferences]=useState(''),[notes,setNotes]=useState(''),[source,setSource]=useState('whatsapp'),[payment,setPayment]=useState('Efectivo'),[paid,setPaid]=useState(false),[shipping,setShipping]=useState(30),[driverPay,setDriverPay]=useState(30),[gift,setGift]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('')
 const products=config.products.filter(p=>p.active&&p.availability==='active'),toppings=config.toppings.filter(t=>t.active)
 const subtotal=useMemo(()=>lines.reduce((sum,l)=>{const p=products.find(x=>x.id===l.productId);return sum+(Number(p?.prices[l.size]||0)+l.toppingIds.reduce((n,id)=>n+Number(toppings.find(t=>t.id===id)?.price||0),0))*l.quantity},0),[lines,products,toppings])
 function update(id:string,patch:Partial<Line>){setLines(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))}
 async function submit(e:FormEvent){e.preventDefault();if(!supabase||busy)return;setBusy(true);setError('');const{data,error}=await supabase.rpc('admin_create_external_order',{p_request_id:crypto.randomUUID(),p_source:source,p_customer_name:name,p_phone:phone,p_items:lines.map(l=>({productId:l.productId,size:l.size,quantity:l.quantity,toppingIds:l.toppingIds})),p_address:{address},p_references:references,p_notes:notes,p_payment_method:payment,p_payment_status:paid?'paid':'pending',p_delivery_fee:shipping,p_driver_pay:driverPay,p_apply_first_purchase:gift});setBusy(false);if(error){setError(error.message);return}setResult(data)}
 if(result)return <main className="min-h-screen bg-[#fffafb] px-5 pb-20 pt-24"><section className="card mx-auto max-w-lg p-7 text-center"><p className="text-4xl">✅</p><h1 className="mt-3 text-2xl font-black">Pedido CAN-{String(result.orderNumber).padStart(6,'0')} creado</h1><p className="mt-2 text-zinc-600">Total validado por el servidor: <strong>{money(result.total)}</strong></p><p className="mt-1 text-sm">{result.customerLinked?'Vinculado a cliente existente.':'Guardado como contacto externo, sin crear una cuenta falsa.'}</p><Link href="/admin/delivery" className="mt-6 flex h-14 items-center justify-center rounded-full bg-cande-500 font-black text-white">Ir a publicar el viaje</Link></section></main>
 return <main className="min-h-screen bg-[#fffafb] px-5 pb-20 pt-24"><form onSubmit={submit} className="mx-auto max-w-3xl"><Link href="/admin/delivery" className="inline-flex items-center gap-2 font-bold text-cande-600"><ArrowLeft size={18}/>Entregas</Link><h1 className="mt-5 text-3xl font-black">Nuevo pedido externo</h1><p className="mt-1 text-sm text-zinc-500">Los precios se validan con el catálogo vigente en Supabase.</p>
 <Section title="Cliente"><div className="grid gap-3 sm:grid-cols-2"><input required className="input" placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/><input required className="input" inputMode="tel" placeholder="Teléfono" value={phone} onChange={e=>setPhone(e.target.value)}/></div><select className="input mt-3" value={source} onChange={e=>setSource(e.target.value)}><option value="whatsapp">WhatsApp</option><option value="messenger">Messenger</option><option value="manual">Manual / llamada</option><option value="other">Otro</option></select></Section>
 <Section title="Entrega"><input required className="input" placeholder="Dirección completa" value={address} onChange={e=>setAddress(e.target.value)}/><input className="input mt-3" placeholder="Referencias" value={references} onChange={e=>setReferences(e.target.value)}/><textarea className="input mt-3 min-h-24" placeholder="Notas" value={notes} onChange={e=>setNotes(e.target.value)}/></Section>
 <Section title="Productos"><div className="space-y-4">{lines.map((line,index)=>{const product=products.find(p=>p.id===line.productId);const sizes=product?Object.keys(product.availableSizes).filter(s=>product.availableSizes[s]):[];return <article key={line.id} className="rounded-md border border-cande-100 p-4"><div className="flex items-center justify-between"><strong>Producto {index+1}</strong><button type="button" onClick={()=>setLines(x=>x.filter(y=>y.id!==line.id))} aria-label="Quitar"><Trash2 size={18}/></button></div><select required className="input mt-3" value={line.productId} onChange={e=>{const p=products.find(x=>x.id===e.target.value);update(line.id,{productId:e.target.value,size:Object.keys(p?.availableSizes||{}).find(s=>p?.availableSizes[s])||'',toppingIds:[]})}}><option value="">Selecciona producto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-3"><select required className="input" value={line.size} onChange={e=>update(line.id,{size:e.target.value})}><option value="">Tamaño</option>{sizes.map(s=><option key={s} value={s}>{s} — {money(product?.prices[s]||0)}</option>)}</select><input className="input" type="number" min="1" max="50" value={line.quantity} onChange={e=>update(line.id,{quantity:Number(e.target.value)})}/></div>{product&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{toppings.filter(t=>!t.productIds.length||t.productIds.includes(product.id)).map(t=><label key={t.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={line.toppingIds.includes(t.id)} onChange={e=>update(line.id,{toppingIds:e.target.checked?[...line.toppingIds,t.id]:line.toppingIds.filter(id=>id!==t.id)})}/>{t.name} +{money(t.price)}</label>)}</div>}</article>})}</div><button type="button" onClick={()=>setLines(x=>[...x,fresh()])} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-full border border-cande-500 font-black text-cande-700"><Plus/>Agregar producto</button></Section>
 <Section title="Cobro y reparto"><div className="grid gap-3 sm:grid-cols-2"><select className="input" value={payment} onChange={e=>setPayment(e.target.value)}><option>Efectivo</option><option>Transferencia / SPEI</option></select><label className="flex items-center gap-2 rounded-md border p-3"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>Pagado previamente</label><label className="text-sm font-bold">Envío cobrado<input className="input mt-1" type="number" min="0" value={shipping} onChange={e=>setShipping(Number(e.target.value))}/></label><label className="text-sm font-bold">Pago al repartidor<input className="input mt-1" type="number" min="0" value={driverPay} onChange={e=>setDriverPay(Number(e.target.value))}/></label></div><label className="mt-4 flex items-start gap-2 rounded-md bg-cande-50 p-3 text-sm"><input type="checkbox" checked={gift} onChange={e=>setGift(e.target.checked)}/><span><strong>Intentar regalo de primera compra</strong><br/>Solo se aplicará si el teléfono pertenece a un cliente registrado y el backend confirma elegibilidad.</span></label><div className="mt-5 space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal estimado</span><strong>{money(subtotal)}</strong></p><p className="flex justify-between"><span>Envío</span><strong>{money(shipping)}</strong></p><p className="flex justify-between border-t pt-3 text-lg"><span>Total cliente</span><strong>{money(subtotal+shipping)}</strong></p><p className="flex justify-between text-cande-700"><span>Ganancia repartidor</span><strong>{money(driverPay)}</strong></p></div></Section>
 {error&&<p className="mt-5 rounded-md bg-red-50 p-3 font-bold text-red-700">{error}</p>}<button disabled={busy||!lines.length} className="mt-6 h-14 w-full rounded-full bg-cande-500 font-black text-white disabled:opacity-50">{busy?'Validando y guardando…':'Crear pedido externo'}</button></form></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card mt-6 p-5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4">{children}</div></section>}
