'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {Bell,Clock3,LogOut,MapPin,PackageCheck,Phone,Power} from 'lucide-react'
import {useAuth} from '@/components/auth-provider'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'
type OrderItem={product_name:string;size_name:string;quantity:number}
type Courier={id:string;name:string;phone:string;status:string;fee_per_delivery:number;delivery_assignments:{id:string;status:string;delivery_fee:number;accepted_at:string;updated_at:string;orders:any}[]}
type Request={id:string;order_id:string;pay:number;pickup_address:string;status:string;order_items:OrderItem[];orders:any}
const next:Record<string,{status:string;label:string}>={accepted:{status:'heading_to_pickup',label:'Voy por el pedido'},heading_to_pickup:{status:'picked_up',label:'Pedido recogido'},picked_up:{status:'delivering',label:'En camino'},delivering:{status:'delivered',label:'Entregado'}}
export default function Driver(){const{user,loading,signOut:authSignOut}=useAuth();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[courier,setCourier]=useState<Courier|null>(null),[requests,setRequests]=useState<Request[]>([]),[notice,setNotice]=useState(''),[realtime,setRealtime]=useState('Conectando'),[alerts,setAlerts]=useState(false);const known=useRef<Set<string>>(new Set()),audio=useRef<AudioContext|null>(null)
 const alertRequest=useCallback((r:Request)=>{navigator.vibrate?.([250,100,250]);if(audio.current){const o=audio.current.createOscillator(),g=audio.current.createGain();o.connect(g);g.connect(audio.current.destination);o.frequency.value=880;g.gain.value=.12;o.start();o.stop(audio.current.currentTime+.35)}if(Notification.permission==='granted')new Notification('Nueva entrega Cande',{body:`CAN-${String(r.orders.order_number).padStart(6,'0')} · ${money(Number(r.pay))}`,icon:'/icons/cande-driver-192.png',tag:`delivery-${r.id}`})},[])
 const load=useCallback(async()=>{if(!supabase||!user)return;const[{data:c,error:courierError},{data:r,error:requestsError}]=await Promise.all([supabase.rpc('driver_dashboard'),supabase.rpc('driver_available_requests')]);if(courierError||requestsError){setNotice(courierError?.message||requestsError?.message||'No se pudieron cargar las solicitudes');return}setCourier(c as unknown as Courier|null);const nextRequests=(r||[]).map((x:any)=>({...x,order_items:x.order_items||[],orders:{id:x.order_id,order_number:x.order_number,total:0,address:{address:x.delivery_address,mapsUrl:x.maps_url}}})) as Request[];if(alerts)nextRequests.filter(x=>!known.current.has(x.id)).forEach(alertRequest);known.current=new Set(nextRequests.map(x=>x.id));setRequests(nextRequests)},[user,alerts,alertRequest])
 useEffect(()=>{load();if(!supabase||!user)return;const ch=supabase.channel(`driver-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'delivery_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'delivery_assignments'},load).on('postgres_changes',{event:'*',schema:'public',table:'delivery_request_rejections'},load).on('postgres_changes',{event:'*',schema:'public',table:'couriers'},load).subscribe(s=>setRealtime(s==='SUBSCRIBED'?'En tiempo real':s==='CHANNEL_ERROR'?'Sin conexion':'Conectando'));return()=>{supabase?.removeChannel(ch)}},[load,user])
 async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)setNotice('Credenciales incorrectas o cuenta sin acceso.')}
 async function availability(value:boolean){const{error}=await supabase!.rpc('driver_availability',{p_available:value});setNotice(error?error.message:value?'Ya estás disponible':'Te desconectaste');await load()}
 async function accept(id:string){const{error}=await supabase!.rpc('accept_delivery',{p_request_id:id});setNotice(error?error.message:'Entrega asignada correctamente');await load()}
 async function reject(id:string){const{error}=await supabase!.rpc('reject_delivery',{p_request_id:id});setNotice(error?error.message:'Solicitud rechazada');await load()}
 async function enableAlerts(){if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();audio.current=new AudioContext();await audio.current.resume();setAlerts(true);setNotice(Notification.permission==='granted'?'Alertas activadas':'Sonido y vibracion activados')}
 async function advance(id:string,status:string){const{error}=await supabase!.rpc('driver_update_delivery',{p_assignment_id:id,p_status:status});setNotice(error?error.message:'Estado actualizado');await load()}
 async function signOut(){if(supabase&&courier)await supabase.rpc('driver_availability',{p_available:false});await authSignOut()}
 if(loading)return <main className="grid min-h-screen place-items-center">Cargando…</main>
 if(!user)return <main className="grid min-h-screen place-items-center bg-cande-50 p-5"><form onSubmit={login} className="card w-full max-w-sm p-7"><h1 className="text-2xl font-black">Cande Repartidor</h1><p className="mt-2 text-sm text-zinc-500">Acceso exclusivo para cuentas DRIVER.</p><input required type="email" className="input mt-6" placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength={8} type="password" className="input mt-3" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/>{notice&&<p className="mt-3 text-sm font-bold text-red-700">{notice}</p>}<button className="mt-4 w-full rounded-full bg-cande-500 py-3 font-black text-white">Iniciar sesión</button></form></main>
 if(user.app_metadata.role!=='DRIVER'||!courier)return <main className="grid min-h-screen place-items-center bg-cande-50 p-5"><section className="card max-w-sm p-7 text-center"><h1 className="text-2xl font-black">Acceso restringido</h1><p className="mt-2 text-sm text-zinc-500">Esta cuenta no está registrada como repartidor.</p><button onClick={signOut} className="mt-5 rounded-full bg-cande-500 px-5 py-3 font-bold text-white">Cerrar sesión</button></section></main>
 const active=courier.delivery_assignments.filter(a=>a.status!=='delivered'&&a.status!=='cancelled'),delivered=courier.delivery_assignments.filter(a=>a.status==='delivered'),today=delivered.filter(a=>new Date(a.updated_at).toDateString()===new Date().toDateString()),activeCount=active.length,full=activeCount>=3
 const availabilityLabel=full?`Completo · ${activeCount}/3 pedidos`:activeCount>0?`Disponible · ${activeCount}/3 pedidos`:courier.status==='available'?'Disponible':'No disponible'
 return <main className="min-h-screen bg-cande-50 p-4"><div className="mx-auto max-w-xl"><header className="rounded-lg bg-cande-900 p-5 text-white"><div className="flex justify-between"><div><p className="text-xs font-bold text-cande-200">Cande Repartidor</p><h1 className="text-2xl font-black">{courier.name}</h1><p className="text-sm">{availabilityLabel}</p></div><button onClick={signOut} aria-label="Cerrar sesión"><LogOut/></button></div><button disabled={activeCount>0} onClick={()=>availability(courier.status!=='available')} className="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black disabled:opacity-50"><Power/>{courier.status==='available'?'DESCONECTARME':'CONECTARME'}</button></header>{notice&&<button onClick={()=>setNotice('')} className="mt-3 w-full rounded-md bg-white p-3 text-sm font-bold">{notice}</button>}<section className="mt-3 grid grid-cols-3 gap-2"><Metric label="Hoy" value={String(today.length)}/><Metric label="Ganancia hoy" value={money(today.reduce((n,a)=>n+Number(a.delivery_fee),0))}/><Metric label="Historial" value={String(delivered.length)}/></section>{activeCount>0&&<section className="mt-7"><div className="flex items-end justify-between gap-3"><h2 className="text-xl font-black">Mis entregas activas</h2><strong className={full?'text-red-700':'text-green-700'}>{activeCount}/3</strong></div>{active.map((assignment,index)=><Active key={assignment.id} number={index+1} assignment={assignment} step={next[assignment.status]} advance={advance}/>)}</section>}<section className="mt-7"><h2 className="text-xl font-black">Solicitudes</h2>{full?<Empty text="3/3 pedidos · Completo"/>:courier.status!=='available'?<Empty text="Conéctate para recibir pedidos"/>:requests.length?requests.map(r=><article key={r.id} className="card mt-4 overflow-hidden border-2 border-cande-500"><div className="bg-cande-500 p-4 text-center font-black text-white">🍓 NUEVA ENTREGA CANDE</div><div className="p-5"><div className="flex justify-between"><strong>PEDIDO CAN-{String(r.orders.order_number).padStart(6,'0')}</strong><strong className="text-green-700">{money(Number(r.pay))}</strong></div><ProductSummary items={r.order_items}/><p className="mt-4 text-sm"><strong className="block text-xs text-zinc-500">Recoger en</strong>{r.pickup_address}</p><p className="mt-3 text-sm"><strong className="block text-xs text-zinc-500">Zona aproximada</strong>{r.orders.address?.address||'Por confirmar'}</p><p className="mt-4 rounded-md bg-zinc-50 p-3 text-xs text-zinc-500">Los datos completos se muestran después de aceptar.</p><button onClick={()=>accept(r.id)} className="mt-4 h-12 w-full rounded-full bg-cande-500 font-black text-white">ACEPTAR PEDIDO</button></div></article>):<Empty text="Esperando solicitudes"/>}</section></div></main>}
function Active({number,assignment,step,advance}:{number:number;assignment:any;step:any;advance:(id:string,status:string)=>void}){const o=assignment.orders;return <article className="card mt-4 p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">Pedido {number}</span><strong>CAN-{String(o.order_number).padStart(6,'0')}</strong></div><ProductSummary items={o.order_items||[]}/><div className="mt-4"><p><strong className="label">Cliente</strong>{o.customers?.name}</p><a className="mt-3 flex gap-2 font-bold text-cande-700" href={`tel:${o.customers?.phone}`}><Phone size={17}/>{o.customers?.phone}</a><p className="mt-3"><strong className="label">Dirección</strong>{o.address?.address}</p><p className="mt-3"><strong className="label">Referencias</strong>{o.references_text||'Sin referencias'}</p><p className="mt-3"><strong className="label">Método de pago</strong>{o.payment_method}</p>{o.address?.mapsUrl&&<a href={o.address.mapsUrl} target="_blank" rel="noreferrer" className="mt-4 flex h-12 items-center justify-center gap-2 rounded-full border border-cande-500 font-bold text-cande-700"><MapPin size={18}/>ABRIR EN GOOGLE MAPS</a>}<p className="mt-4 flex justify-between border-t pt-4"><span>Total a cobrar</span><strong>{money(Number(o.total))}</strong></p></div>{step&&<button onClick={()=>advance(assignment.id,step.status)} className="mt-5 flex h-14 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white"><PackageCheck/>{step.label}</button>}</article>}
function ProductSummary({items}:{items:OrderItem[]}){return <div className="mt-4 space-y-2 border-y border-cande-100 bg-cande-50 px-3 py-4">{items.length?items.map((item,index)=><p key={`${item.product_name}-${item.size_name}-${index}`} className="text-lg font-black uppercase leading-tight text-cande-900"><span aria-hidden="true">🍓 </span>{item.quantity} × {item.product_name} <span className="whitespace-nowrap">— {item.size_name}</span></p>):<p className="font-bold text-zinc-500">Productos por confirmar</p>}</div>}
function Metric({label,value}:{label:string;value:string}){return <article className="rounded-md bg-white p-3 text-center"><strong>{value}</strong><span className="block text-[10px] text-zinc-500">{label}</span></article>};function Empty({text}:{text:string}){return <div className="mt-4 rounded-lg bg-white p-8 text-center"><Clock3 className="mx-auto text-cande-300"/><p className="mt-3 font-bold">{text}</p></div>}
