'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {ChevronRight,Gift,LogOut,Phone,ReceiptText,ShieldCheck,Star,Users} from 'lucide-react'
import {normalizeMexicanPhone,useAuth} from '@/components/auth-provider'
import {REFERRAL_STORAGE_KEY} from '@/components/referral-capture'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'
const SAFE_NEXT_PATHS=new Set(['/','/account','/account/referrals','/menu','/cart','/checkout','/orders','/rewards'])

export default function Account(){
 const{user,profile,loading,refreshProfile,signOut}=useAuth();const router=useRouter()
 const[mode,setMode]=useState<'login'|'register'>('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[spent,setSpent]=useState(0)
 useEffect(()=>{if(!user||!supabase)return;supabase.from('orders').select('total').neq('status','cancelled').then(({data})=>setSpent((data||[]).reduce((n,row)=>n+Number(row.total),0)))},[user])
 async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return setError('Supabase no está configurado.');if(password.length<8)return setError('Usa una contraseña de al menos 8 caracteres.');const cleanEmail=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(cleanEmail))return setError('Escribe un correo electrónico válido.');let normalized='';if(mode==='register'){normalized=normalizeMexicanPhone(phone);if(!/^\+52\d{10}$/.test(normalized))return setError('Escribe un WhatsApp mexicano de 10 dígitos.')}setBusy(true);setError('');setNotice('');const referralCode=mode==='register'?localStorage.getItem(REFERRAL_STORAGE_KEY)||undefined:undefined;const result=mode==='register'?await supabase.auth.signUp({email:cleanEmail,password,options:{data:{name:name.trim(),phone:normalized,referral_code:referralCode},emailRedirectTo:`${window.location.origin}/account`}}):await supabase.auth.signInWithPassword({email:cleanEmail,password});setBusy(false);if(result.error){setError(result.error.message);return}if(mode==='register')localStorage.removeItem(REFERRAL_STORAGE_KEY);if(mode==='register'&&!result.data.session){setNotice('Cuenta creada. Revisa tu correo y confirma el enlace antes de iniciar sesión.');setMode('login');setPassword('');return}await refreshProfile();const requested=new URLSearchParams(window.location.search).get('next')||'/account';router.replace(SAFE_NEXT_PATHS.has(requested)?requested:'/');router.refresh()}
 if(loading)return <main className="page"><p className="text-center text-sm text-zinc-500">Cargando tu cuenta…</p></main>
 if(!user||!profile)return <main className="page max-w-md"><p className="text-xs font-bold uppercase text-cande-500">Cuenta Cande</p><h1 className="mt-1 text-3xl font-black">{mode==='login'?'Inicia sesión':'Crea tu cuenta'}</h1><p className="mt-2 text-sm text-zinc-500">Tus pedidos y puntos quedarán guardados para que puedas entrar desde cualquier celular.</p><div className="mt-6 grid grid-cols-2 rounded-md bg-cande-50 p-1"><button onClick={()=>{setMode('login');setError('');setNotice('')}} className={`rounded px-3 py-2 text-sm font-bold ${mode==='login'?'bg-white text-cande-700 shadow-sm':'text-zinc-500'}`}>Entrar</button><button onClick={()=>{setMode('register');setError('');setNotice('')}} className={`rounded px-3 py-2 text-sm font-bold ${mode==='register'?'bg-white text-cande-700 shadow-sm':'text-zinc-500'}`}>Registrarme</button></div>{notice&&<p role="status" className="mt-4 rounded-md bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{notice}</p>}<form onSubmit={submit} className="card mt-5 space-y-4 p-5">{mode==='register'&&<label><span className="label">Nombre</span><input required minLength={2} className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre" autoComplete="name"/></label>}<label><span className="label">Correo electrónico</span><input required className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com" type="email" inputMode="email" autoComplete="email"/></label>{mode==='register'&&<label><span className="label">Número de WhatsApp</span><input required className="input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="722 123 4567" inputMode="tel" autoComplete="tel"/></label>}<label><span className="label">Contraseña</span><input required minLength={8} className="input" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Mínimo 8 caracteres" autoComplete={mode==='login'?'current-password':'new-password'}/></label>{error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<button disabled={busy} className="h-13 w-full rounded-full bg-cande-500 py-3 font-bold text-white disabled:opacity-50">{busy?'Procesando…':mode==='login'?'Iniciar sesión':'Crear mi cuenta'}</button></form><p className="mt-4 flex items-start gap-2 text-xs leading-relaxed text-zinc-500"><ShieldCheck size={16} className="shrink-0 text-cande-600"/>Tu contraseña se administra con Supabase Auth. Cande no puede verla.</p></main>
 const initials=profile.name.split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase();const level=profile.customer_levels?.name||'Fresa';const rows=[[ReceiptText,'Historial de pedidos','/orders'],[Gift,'Recompensas disponibles','/rewards'],[Users,'Invita y Gana','/account/referrals']]as const
 return <main className="page max-w-2xl"><section className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-cande-100 text-xl font-black text-cande-700">{initials}</span><div><h1 className="text-2xl font-black">{profile.name}</h1><p className="mt-1 flex items-center gap-1 text-sm text-zinc-500"><Phone size={14}/>{profile.phone}</p></div></section><section className="mt-7 grid grid-cols-3 divide-x divide-cande-100 rounded-lg bg-cande-900 p-5 text-center text-white"><div><strong className="block text-xl">{profile.points_balance}</strong><span className="text-[11px] text-white/60">Puntos</span></div><div><strong className="block text-xl">{level}</strong><span className="text-[11px] text-white/60">Nivel</span></div><div><strong className="block text-xl">{money(spent)}</strong><span className="text-[11px] text-white/60">Gastado</span></div></section><section className="card mt-5 flex items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-full bg-cande-100 text-cande-600"><Star fill="currentColor" size={18}/></span><div><strong>Saldo Rewards</strong><p className="mt-1 text-sm text-zinc-500">{profile.points_balance} puntos disponibles para canjear.</p></div></section><section className="mt-7 overflow-hidden rounded-lg border border-cande-100 bg-white">{rows.map(([Icon,label,href])=><Link key={label} href={href} className="flex items-center gap-3 border-b border-cande-50 p-4 last:border-0"><Icon size={19} className="text-cande-600"/><span className="flex-1 text-sm font-bold">{label}</span><ChevronRight size={17} className="text-zinc-400"/></Link>)}</section><button onClick={async()=>{await signOut();router.replace('/')}} className="mt-6 flex items-center gap-2 text-sm font-bold text-zinc-500"><LogOut size={17}/>Cerrar sesión</button></main>
}
