'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Bike,CheckCircle2,Clock3,MapPin,PackageCheck,Phone,Send,UserCheck,Users} from 'lucide-react'
import {demoOrders,DeliveryOrder,DeliveryRequest,drivers,PRESENCE_KEY,readRequests,writeRequests,zoneFromAddress} from '@/lib/delivery-demo'
import {money} from '@/lib/data'

const stageLabels:Record<string,string>={requested:'Buscando repartidor',assigned:'Asignado',heading_to_pickup:'Voy por el pedido',picked_up:'Pedido recogido',delivering:'En camino',delivered:'Entregado'}

export default function DeliveryAdmin(){
 const[orders,setOrders]=useState<DeliveryOrder[]>(demoOrders);const[requests,setRequests]=useState<DeliveryRequest[]>([]);const[presence,setPresence]=useState<Record<string,{connected:boolean;updatedAt:string}>>({})
 function sync(){setRequests(readRequests());try{setPresence(JSON.parse(localStorage.getItem(PRESENCE_KEY)||'{}'))}catch{}}
 useEffect(()=>{try{const saved:DeliveryOrder[]=JSON.parse(localStorage.getItem('cande-orders')||'[]');const home=saved.filter(o=>o.delivery?.type==='delivery'&&o.status!=='Entregado');if(home.length)setOrders([...home,...demoOrders])}catch{}sync();const timer=setInterval(sync,1500);addEventListener('storage',sync);addEventListener('cande-delivery-update',sync);return()=>{clearInterval(timer);removeEventListener('storage',sync);removeEventListener('cande-delivery-update',sync)}},[])
 const active=useMemo(()=>requests.filter(r=>r.stage!=='delivered'),[requests]);const connected=Object.values(presence).filter(p=>p.connected).length;const available=connected
 function requestDriver(order:DeliveryOrder){if(readRequests().some(r=>r.order.orderId===order.orderId&&r.stage!=='delivered'))return;const now=new Date().toISOString();const request:DeliveryRequest={order,pickupZone:'Sucursal Cande · Toluca Centro',pickupAddress:'Fresas con Crema Cande, sucursal principal',deliveryZone:zoneFromAddress(order.delivery.address),pay:35,stage:'requested',requestedAt:now,updatedAt:now};writeRequests([...readRequests(),request]);sync()}
 function cancel(orderId:string){writeRequests(readRequests().filter(r=>r.order.orderId!==orderId));sync()}
 return <main className="min-h-screen bg-[#fffafb] px-5 pb-20 pt-24"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin" className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-cande-600"><ArrowLeft size={17}/>Volver al dashboard</Link><p className="text-xs font-bold uppercase text-cande-500">Operación de entregas</p><h1 className="mt-1 text-3xl font-black">Repartidores</h1><p className="mt-2 text-sm text-zinc-500">Solicita, asigna y sigue cada entrega en tiempo real.</p></div><Link href="/driver" className="rounded-full bg-cande-500 px-5 py-3 text-sm font-bold text-white">Abrir portal de repartidor</Link></header>
 <section className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={Users} label="Repartidores" value="4"/><Stat icon={UserCheck} label="Disponibles" value={String(available)}/><Stat icon={Bike} label="Entregas activas" value={String(active.length)}/><Stat icon={PackageCheck} label="Entregas históricas" value="115"/></section>
 <section className="mt-10"><div className="flex items-center justify-between"><h2 className="section-title">Pedidos a domicilio</h2><span className="rounded-full bg-cande-100 px-3 py-1 text-xs font-bold text-cande-700">{orders.length}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{orders.map(order=>{const request=requests.find(r=>r.order.orderId===order.orderId);const assigned=drivers.find(d=>d.id===request?.driverId);return <article key={order.orderId} className="card p-5"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-cande-500">{order.orderId}</p><h3 className="mt-1 text-lg font-black">{order.customer.name}</h3><a href={`tel:${order.customer.phone.replace(/\D/g,'')}`} className="mt-1 flex items-center gap-1 text-xs text-zinc-500"><Phone size={13}/>{order.customer.phone}</a></div><strong>{money(order.total)}</strong></div><div className="mt-4 rounded-md bg-cande-50 p-4 text-sm"><p className="flex gap-2"><MapPin size={16} className="shrink-0 text-cande-600"/>{order.delivery.address}</p>{order.delivery.references&&<p className="mt-2 text-xs text-zinc-500">Ref: {order.delivery.references}</p>}{order.delivery.mapsUrl&&<a href={order.delivery.mapsUrl} target="_blank" rel="noreferrer" className="mt-2 block text-xs font-bold text-cande-600">Abrir ubicación en Maps</a>}</div>{!request?<button onClick={()=>requestDriver(order)} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white"><Send size={17}/>Solicitar repartidor</button>:<div className={`mt-4 rounded-md border p-4 ${request.stage==='delivered'?'border-green-200 bg-green-50':'border-amber-200 bg-amber-50'}`}><div className="flex items-center gap-2"><Clock3 size={18}/><strong>{stageLabels[request.stage]}</strong></div>{assigned&&<p className="mt-2 text-sm">Repartidor: <strong>{assigned.name}</strong></p>}<p className="mt-1 text-xs text-zinc-500">Pago: {money(request.pay)} · Actualizado {new Date(request.updatedAt).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</p>{request.stage==='requested'&&<button onClick={()=>cancel(order.orderId)} className="mt-3 text-xs font-bold text-red-600">Cancelar solicitud</button>}</div>}</article>})}</div></section>
 <section className="mt-10"><h2 className="section-title">Equipo de reparto</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{drivers.map(d=><article key={d.id} className="card p-5"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-cande-100 font-black text-cande-700">{d.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><Status status={d.status}/></div><h3 className="mt-4 font-black">{d.name}</h3><p className="mt-1 text-xs text-zinc-500">{d.phone}</p><div className="mt-4 space-y-2 border-t pt-4 text-sm"><Row label="Asignados" value={String(d.assigned)}/><Row label="Entregados" value={String(d.delivered)}/><Row label="Pago" value={money(d.fee)}/><Row label="Actividad" value={d.lastActivity}/></div></article>)}</div></section></div></main>
}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <article className="card p-4"><Icon size={19} className="text-cande-600"/><strong className="mt-4 block text-2xl font-black">{value}</strong><span className="text-xs font-bold text-zinc-500">{label}</span></article>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between"><span className="text-zinc-500">{label}</span><strong className="text-xs">{value}</strong></div>}
function Status({status}:{status:string}){const s=status==='Disponible'?'bg-green-100 text-green-700':status==='Ocupado'?'bg-amber-100 text-amber-700':'bg-zinc-100 text-zinc-500';return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${s}`}>{status}</span>}
