'use client'

import Link from 'next/link'
import {useCallback,useEffect,useState} from 'react'
import {ArrowLeft,Bike,ChevronRight,Clock3,MapPin,PackageCheck,Phone,Send,UserCheck,Users,X} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'

type Item={id:string;product_name:string;size_name:string;unit_price:number;quantity:number;toppings:{name:string;price:number}[];line_total:number}
type Assignment={id:string;order_id:string;status:string;delivery_fee:number;accepted_at:string;updated_at:string;heading_to_pickup_at:string|null;picked_up_at:string|null;delivering_at:string|null;delivered_at:string|null;couriers:Courier|null}
type Request={id:string;order_id:string;status:string;pay:number;requested_at:string;assigned_at:string|null;delivery_assignments:Assignment[]}
type Order={id:string;customer_id:string;order_number:number;status:string;delivery_type:string;address:any;references_text:string|null;notes:string|null;payment_method:string;payment_status:string;subtotal:number;delivery_fee:number;discount:number;total:number;points_earned:number;created_at:string;delivered_at:string|null;customers:{name:string;phone:string}|null;order_items:Item[];delivery_requests:Request[]}
type Courier={id:string;name:string;phone:string;status:string;fee_per_delivery:number;last_activity_at:string|null;delivery_assignments:Assignment[]}

const labels:Record<string,string>={pending:'Nuevo',confirmed:'Confirmado',preparing:'Preparando',ready:'Listo',requested:'Buscando repartidor',assigned:'Asignado',accepted:'Asignado',heading_to_pickup:'Recogiendo pedido',picked_up:'Pedido recogido',delivering:'En camino',delivered:'Entregado',cancelled:'Cancelado'}
const next:Record<string,{status:string;label:string}>={pending:{status:'confirmed',label:'Aceptar pedido'},confirmed:{status:'preparing',label:'Comenzar preparación'},preparing:{status:'ready',label:'Marcar listo'}}
const activeStatuses=['accepted','heading_to_pickup','picked_up','delivering']

export default function DeliveryAdmin(){
 const[orders,setOrders]=useState<Order[]>([]),[couriers,setCouriers]=useState<Courier[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Order|null>(null),[selectedCourier,setSelectedCourier]=useState<Courier|null>(null)
 const load=useCallback(async()=>{if(!supabase)return;const[or,cr,rr,ar,ir]=await Promise.all([
  supabase.from('orders').select('id,customer_id,order_number,status,delivery_type,address,references_text,notes,payment_method,payment_status,subtotal,delivery_fee,discount,total,points_earned,created_at,delivered_at').order('created_at',{ascending:false}),
  supabase.from('customers').select('id,name,phone'),
  supabase.from('delivery_requests').select('id,order_id,status,pay,requested_at,assigned_at'),
  supabase.from('couriers').select('id,name,phone,status,fee_per_delivery,last_activity_at,delivery_assignments(id,order_id,status,delivery_fee,accepted_at,updated_at,heading_to_pickup_at,picked_up_at,delivering_at,delivered_at,courier_id)'),
  supabase.from('order_items').select('id,order_id,product_name,size_name,unit_price,quantity,toppings,line_total')
 ]);const error=or.error||cr.error||rr.error||ar.error||ir.error;if(error){setNotice(`No se pudieron cargar los datos: ${error.message}`);return}
  const customerMap=new Map((cr.data||[]).map((c:any)=>[c.id,c])),courierRows=(ar.data||[]) as any[],courierMap=new Map(courierRows.map((c:any)=>[c.id,c])),assignments=courierRows.flatMap((c:any)=>(c.delivery_assignments||[]).map((a:any)=>({...a,couriers:courierMap.get(a.courier_id)||null}))),requests=(rr.data||[]).map((r:any)=>({...r,delivery_assignments:assignments.filter((a:any)=>a.order_id===r.order_id)})),items=ir.data||[]
  const nextOrders=(or.data||[]).map((o:any)=>({...o,customers:customerMap.get(o.customer_id)||null,order_items:items.filter((i:any)=>i.order_id===o.id),delivery_requests:requests.filter((r:any)=>r.order_id===o.id)})) as Order[]
  const nextCouriers=courierRows.map((c:any)=>({...c,delivery_assignments:(c.delivery_assignments||[]).map((a:any)=>({...a,couriers:c}))})) as Courier[]
  setOrders(nextOrders);setCouriers(nextCouriers);setSelected(current=>current?nextOrders.find(o=>o.id===current.id)||null:null);setSelectedCourier(current=>current?nextCouriers.find(c=>c.id===current.id)||null:null)
 },[])
 useEffect(()=>{load();if(!supabase)return;const ch=supabase.channel('admin-operations').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'delivery_requests'},load).on('postgres_changes',{event:'*',schema:'public',table:'delivery_assignments'},load).on('postgres_changes',{event:'*',schema:'public',table:'couriers'},load).subscribe();return()=>{supabase?.removeChannel(ch)}},[load])
 async function advance(order:Order){const step=next[order.status];if(!step||!supabase)return;setBusy(order.id);const{error}=await supabase.rpc('admin_set_order_status',{p_order_id:order.id,p_status:step.status});setBusy('');setNotice(error?error.message:'Estado actualizado correctamente');await load()}
 async function request(order:Order){if(!supabase)return;setBusy(order.id);const pay=couriers.find(c=>c.status==='available')?.fee_per_delivery||35;const{error}=await supabase.rpc('request_driver',{p_order_id:order.id,p_pay:pay,p_pickup_address:'Fresas con Crema Cande, sucursal principal'});setBusy('');setNotice(error?error.message:'Solicitud enviada a repartidores disponibles');await load()}
 const available=couriers.filter(c=>c.status==='available').length,active=couriers.reduce((n,c)=>n+activeFor(c).length,0),delivered=couriers.reduce((n,c)=>n+c.delivery_assignments.filter(a=>a.status==='delivered').length,0)
 return <main className="min-h-screen bg-[#fffafb] px-5 pb-20 pt-24"><div className="mx-auto max-w-7xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-cande-600"><ArrowLeft size={17}/>Dashboard</Link><header className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase text-cande-500">Centro de control en tiempo real</p><h1 className="text-3xl font-black">Pedidos y repartidores</h1></div><Link href="/driver" className="rounded-full bg-cande-500 px-5 py-3 text-sm font-bold text-white">Portal repartidor</Link></header>{notice&&<button onClick={()=>setNotice('')} className="mt-5 w-full rounded-md bg-cande-50 p-3 text-sm font-bold text-cande-800">{notice}</button>}<section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={Users} label="Repartidores" value={couriers.length}/><Stat icon={UserCheck} label="Disponibles" value={available}/><Stat icon={Bike} label="Entregas activas" value={active}/><Stat icon={PackageCheck} label="Entregadas" value={delivered}/></section><section className="mt-9"><h2 className="section-title">Pedidos</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{orders.map(o=><OrderCard key={o.id} order={o} busy={busy} available={available} open={()=>setSelected(o)} advance={advance} request={request}/>)}</div></section><section className="mt-10"><h2 className="section-title">Equipo</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{couriers.map(c=>{const own=activeFor(c);return <button key={c.id} onClick={()=>setSelectedCourier(c)} className="card p-5 text-left"><div className="flex justify-between gap-3"><strong>{c.name}</strong><Status status={c.status}/></div><p className="mt-1 text-xs text-zinc-500">{c.phone}</p><p className="mt-4 text-sm font-black text-cande-700">{c.name} — {own.length}/3 pedidos activos</p><p className="mt-2 text-sm">Entregadas: <strong>{c.delivery_assignments.filter(a=>a.status==='delivered').length}</strong></p><span className="mt-4 flex items-center justify-end gap-1 text-xs font-bold text-cande-600">Ver pedidos <ChevronRight size={15}/></span></button>})}</div></section></div>{selected&&<OrderDetail order={selected} close={()=>setSelected(null)}/>} {selectedCourier&&<CourierDetail courier={selectedCourier} orders={orders} close={()=>setSelectedCourier(null)} open={o=>{setSelectedCourier(null);setSelected(o)}}/>}</main>}

function OrderCard({order,busy,available,open,advance,request}:{order:Order;busy:string;available:number;open:()=>void;advance:(o:Order)=>void;request:(o:Order)=>void}){const req=order.delivery_requests[0],assignment=req?.delivery_assignments[0],stage=assignment?.status||req?.status||order.status;return <article className="card p-5"><button onClick={open} className="w-full text-left"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold text-cande-500">CAN-{String(order.order_number).padStart(6,'0')}</p><h3 className="font-black">{order.customers?.name}</h3></div><strong>{money(Number(order.total))}</strong></div><p className="mt-3 flex items-center gap-2 text-sm font-bold"><Clock3 size={16}/>{labels[stage]||stage}</p>{order.delivery_type==='delivery'&&<p className="mt-3 flex gap-2 rounded-md bg-cande-50 p-3 text-sm"><MapPin size={16}/>{order.address?.address||'Dirección pendiente'}</p>}{assignment?.couriers&&<p className="mt-3 text-sm">Repartidor: <strong>{assignment.couriers.name}</strong></p>}<span className="mt-4 flex items-center justify-end gap-1 text-xs font-bold text-cande-600">Ver pedido completo <ChevronRight size={15}/></span></button>{next[order.status]&&<button disabled={busy===order.id} onClick={()=>advance(order)} className="mt-4 h-12 w-full rounded-full bg-cande-900 font-black text-white disabled:opacity-50">{next[order.status].label}</button>}{order.delivery_type==='delivery'&&order.status==='ready'&&!req&&<button disabled={busy===order.id||available===0} onClick={()=>request(order)} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white disabled:opacity-50"><Send size={17}/>{available?'Solicitar repartidor':'Sin repartidores disponibles'}</button>}</article>}

function OrderDetail({order,close}:{order:Order;close:()=>void}){const req=order.delivery_requests[0],a=req?.delivery_assignments[0],stage=a?.status||req?.status||order.status,maps=order.address?.mapsUrl||order.address?.maps_url;return <Modal close={close} title={`Pedido CAN-${String(order.order_number).padStart(6,'0')}`}><p className="text-sm text-zinc-500">{formatDate(order.created_at)}</p><StatusFlow stage={stage}/><Section title="Cliente y entrega"><Detail label="Cliente" value={order.customers?.name}/><Detail label="Teléfono" value={order.customers?.phone}/><Detail label="Tipo de entrega" value={order.delivery_type==='delivery'?'Envío a domicilio':'Recoger pedido'}/><Detail label="Dirección" value={order.address?.address||'Sin dirección'}/><Detail label="Referencias e instrucciones" value={order.references_text||'Sin referencias'}/>{maps?<a href={maps} target="_blank" rel="noreferrer" className="mt-3 flex h-12 items-center justify-center gap-2 rounded-full border border-cande-500 font-bold text-cande-700"><MapPin size={18}/>ABRIR UBICACIÓN</a>:<Detail label="Ubicación" value="No compartida"/>}</Section><Section title="Productos">{order.order_items.map(i=><div key={i.id} className="border-b border-cande-100 py-3 last:border-0"><div className="flex justify-between gap-4"><strong>{i.quantity} × {i.product_name} — {i.size_name}</strong><strong>{money(Number(i.line_total))}</strong></div><p className="text-xs text-zinc-500">Precio unitario: {money(Number(i.unit_price))}</p><p className="mt-1 text-sm">Toppings: {i.toppings?.length?i.toppings.map(t=>`${t.name} (${money(Number(t.price))})`).join(', '):'Sin toppings'}</p></div>)}</Section><Section title="Cobro"><MoneyRow label="Subtotal" value={order.subtotal}/><MoneyRow label="Envío" value={order.delivery_fee}/><MoneyRow label="Descuentos o recompensas" value={-Number(order.discount)}/><MoneyRow label="Total final" value={order.total} strong/><Detail label="Método de pago" value={order.payment_method}/><Detail label="Estado de pago" value={order.payment_status}/><Detail label="Puntos ganados" value={`${order.points_earned} puntos`}/></Section><Section title="Notas especiales"><p className="text-sm">{order.notes||'Sin notas especiales'}</p></Section><Section title="Información del reparto"><Detail label="Repartidor asignado" value={a?.couriers?.name||'Sin asignar'}/><Detail label="Estado del repartidor" value={a?.couriers?courierLabel(a.couriers,activeFor(a.couriers).length):'Sin asignar'}/><Detail label="Hora de aceptación" value={formatDate(a?.accepted_at)}/><Detail label="Estado actual" value={labels[stage]||stage}/><Detail label="Hora en que salió" value={formatDate(a?.delivering_at)}/><Detail label="Hora de entrega" value={formatDate(a?.delivered_at||order.delivered_at)}/></Section></Modal>}

function CourierDetail({courier,orders,close,open}:{courier:Courier;orders:Order[];close:()=>void;open:(o:Order)=>void}){const active=activeFor(courier);return <Modal close={close} title={courier.name}><p className="font-black text-cande-700">{courierLabel(courier,active.length)}</p><p className="mt-1 text-sm text-zinc-500">{courier.phone}</p><Section title="Pedidos activos">{active.length?active.map(a=>{const o=orders.find(row=>row.id===a.order_id);return <button key={a.id} disabled={!o} onClick={()=>o&&open(o)} className="flex w-full items-center justify-between border-b border-cande-100 py-4 text-left last:border-0"><span><strong className="block">CAN-{o?String(o.order_number).padStart(6,'0'):'—'}</strong><small>{labels[a.status]||a.status}</small></span><ChevronRight/></button>}):<p className="text-sm text-zinc-500">Sin entregas activas.</p>}</Section></Modal>}

function StatusFlow({stage}:{stage:string}){const steps=['pending','preparing','ready','assigned','delivering','delivered'],normalized=stage==='confirmed'?'pending':stage==='requested'?'ready':stage==='accepted'||stage==='heading_to_pickup'||stage==='picked_up'?'assigned':stage,index=steps.indexOf(normalized);return <div className="mt-5 overflow-x-auto"><div className="flex min-w-[560px] items-center">{steps.map((s,i)=><div key={s} className="flex flex-1 items-center last:flex-none"><span className={`grid h-8 min-w-8 place-items-center rounded-full text-xs font-black ${i<=index?'bg-cande-500 text-white':'bg-zinc-100 text-zinc-400'}`}>{i+1}</span><span className={`mx-2 text-xs font-bold ${i<=index?'text-cande-700':'text-zinc-400'}`}>{labels[s]}</span>{i<steps.length-1&&<span className={`h-0.5 flex-1 ${i<index?'bg-cande-500':'bg-zinc-200'}`}/>}</div>)}</div></div>}
function Modal({close,title,children}:{close:()=>void;title:string;children:React.ReactNode}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/45 p-3 sm:p-6"><div className="mx-auto min-h-full max-w-3xl rounded-lg bg-[#fffafb] p-5 shadow-2xl sm:p-7"><header className="flex items-start justify-between gap-4"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} aria-label="Cerrar" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-white"><X/></button></header>{children}</div></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-6 border-t border-cande-100 pt-5"><h3 className="text-lg font-black">{title}</h3><div className="mt-3">{children}</div></section>}
function Detail({label,value}:{label:string;value:React.ReactNode}){return <p className="mt-3 text-sm"><strong className="block text-xs text-zinc-500">{label}</strong>{value||'No registrado'}</p>}
function MoneyRow({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <p className={`flex justify-between py-1 ${strong?'mt-2 border-t pt-3 text-lg font-black':''}`}><span>{label}</span><span>{money(Number(value))}</span></p>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:number}){return <article className="card p-4"><Icon className="text-cande-600" size={19}/><strong className="mt-3 block text-2xl">{value}</strong><span className="text-xs text-zinc-500">{label}</span></article>}
function Status({status}:{status:string}){return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${status==='available'?'bg-green-100 text-green-700':status==='busy'?'bg-amber-100 text-amber-700':'bg-zinc-100 text-zinc-500'}`}>{status==='available'?'Disponible':status==='busy'?'Completo':'Desconectado'}</span>}
function activeFor(courier:Courier){return courier.delivery_assignments.filter(a=>activeStatuses.includes(a.status))}
function courierLabel(courier:Courier,count:number){return `${courier.name} — ${count}/3 pedidos activos`}
function formatDate(value?:string|null){return value?new Date(value).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}):'No registrado'}
