'use client'

import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import Link from 'next/link'
import {Bell,Check,ExternalLink,Settings,Volume2,VolumeX,X} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {useAuth} from '@/components/auth-provider'

type Receipt={read_at:string|null;attended_at:string|null}
export type AdminNotice={id:string;event_key:string;type:string;title:string;description:string;action_href:string|null;created_at:string;admin_notification_receipts?:Receipt[]}
export type AdminPreferences={heads_up_enabled:boolean;sound_enabled:boolean;vibration_enabled:boolean;browser_notifications_enabled:boolean}
export const defaultAdminPreferences:AdminPreferences={heads_up_enabled:true,sound_enabled:true,vibration_enabled:true,browser_notifications_enabled:false}

export function AdminNotificationHub(){
 const{user}=useAuth()
 const[items,setItems]=useState<AdminNotice[]>([]),[open,setOpen]=useState(false),[head,setHead]=useState<AdminNotice|null>(null),[prefs,setPrefs]=useState(defaultAdminPreferences)
 const audio=useRef<AudioContext|null>(null),known=useRef(new Set<string>()),ready=useRef(false)
 const load=useCallback(async()=>{if(!supabase||!user)return;const{data,error}=await supabase.from('admin_notifications').select('id,event_key,type,title,description,action_href,created_at,admin_notification_receipts!left(read_at,attended_at)').order('created_at',{ascending:false}).limit(100);if(!error){const next=(data||[])as unknown as AdminNotice[];setItems(next);known.current=new Set(next.map(n=>n.id))}},[user])
 const loadPrefs=useCallback(async()=>{if(!supabase||!user)return;const{data}=await supabase.from('admin_notification_preferences').select('heads_up_enabled,sound_enabled,vibration_enabled,browser_notifications_enabled').eq('user_id',user.id).maybeSingle();if(data)setPrefs(data)},[user])
 const alert=useCallback((notice:AdminNotice)=>{if(prefs.heads_up_enabled)setHead(notice);if(prefs.sound_enabled){audio.current||=new AudioContext();void audio.current.resume();const c=audio.current,o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.1,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.45);o.start();o.stop(c.currentTime+.45)}if(prefs.vibration_enabled)navigator.vibrate?.([300,120,300,120,600]);if(prefs.browser_notifications_enabled&&'Notification'in window&&Notification.permission==='granted'&&document.hidden)new Notification(notice.title,{body:notice.description,tag:notice.event_key,requireInteraction:true,data:{url:notice.action_href||'/admin/notifications'}})},[prefs])
 useEffect(()=>{if(!user)return;void Promise.all([load(),loadPrefs()]).then(()=>{ready.current=true});return()=>{ready.current=false}},[load,loadPrefs,user])
 useEffect(()=>{if(!supabase||!user)return;const client=supabase,channel=client.channel(`admin-notifications-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_notifications'},payload=>{const notice=payload.new as AdminNotice;if(known.current.has(notice.id))return;known.current.add(notice.id);setItems(current=>[notice,...current].slice(0,100));if(ready.current)alert(notice)}).subscribe();return()=>{void client.removeChannel(channel)}},[alert,user])
 const unread=useMemo(()=>items.filter(n=>!n.admin_notification_receipts?.[0]?.read_at).length,[items])
 async function mark(n:AdminNotice,attended=false){if(!supabase||!user)return;const now=new Date().toISOString(),old=n.admin_notification_receipts?.[0],receipt={read_at:old?.read_at||now,attended_at:attended?(old?.attended_at||now):old?.attended_at||null};await supabase.from('admin_notification_receipts').upsert({notification_id:n.id,user_id:user.id,...receipt},{onConflict:'notification_id,user_id'});setItems(current=>current.map(item=>item.id===n.id?{...item,admin_notification_receipts:[receipt]}:item));if(head?.id===n.id)setHead(null)}
 async function toggle(){const opening=!open;setOpen(opening);if(opening)await Promise.all(items.filter(n=>!n.admin_notification_receipts?.[0]?.read_at).map(n=>mark(n)))}
 return <><button onClick={()=>void toggle()} className="fixed right-3 top-2 z-[70] grid h-11 w-11 place-items-center rounded-full bg-cande-900 text-white shadow-lg" aria-label={`Notificaciones${unread?`, ${unread} sin leer`:''}`}><Bell size={19}/>{unread>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-cande-500 px-1 text-[10px] font-black">{unread>99?'99+':unread}</span>}</button>{head&&<section role="alert" className="fixed inset-x-3 top-16 z-[80] mx-auto max-w-lg rounded-lg bg-cande-900 p-4 text-white shadow-2xl"><div className="flex gap-3"><Bell className="shrink-0 text-cande-300"/><div className="min-w-0 flex-1"><strong>{head.title}</strong><p className="mt-1 text-sm text-white/80">{head.description}</p><div className="mt-3 flex gap-2">{head.action_href&&<Link onClick={()=>void mark(head)} href={head.action_href} className="rounded-full bg-cande-500 px-3 py-2 text-xs font-black">Ver pedido</Link>}<button onClick={()=>void mark(head,true)} className="rounded-full bg-white/15 px-3 py-2 text-xs font-black">Atendido</button></div></div><button onClick={()=>setHead(null)} aria-label="Cerrar"><X size={18}/></button></div></section>}{open&&<section className="fixed right-3 top-16 z-[75] w-[min(25rem,calc(100vw-24px))] rounded-lg bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><strong>Notificaciones</strong><div className="flex gap-3"><span title={prefs.sound_enabled?'Sonido activo':'Sonido inactivo'}>{prefs.sound_enabled?<Volume2 size={18}/>:<VolumeX size={18}/>}</span><Link href="/admin/notifications#preferences" onClick={()=>setOpen(false)} aria-label="Preferencias"><Settings size={18}/></Link></div></div><div className="mt-3 max-h-[60vh] space-y-2 overflow-y-auto">{items.map(n=>{const receipt=n.admin_notification_receipts?.[0];return <article key={n.id} className={`rounded-md p-3 ${receipt?.read_at?'bg-zinc-50':'bg-cande-50'}`}><div className="flex gap-2"><div className="min-w-0 flex-1"><strong className="text-sm">{n.title}</strong><p className="mt-1 text-xs text-zinc-600">{n.description}</p>{n.action_href&&<Link href={n.action_href} onClick={()=>void mark(n)} className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-cande-700">Abrir <ExternalLink size={12}/></Link>}</div>{receipt?.attended_at?<span title="Atendida"><Check size={17} className="text-emerald-600"/></span>:<button onClick={()=>void mark(n,true)} aria-label="Marcar atendida"><Check size={17}/></button>}</div></article>})}{!items.length&&<p className="py-5 text-center text-sm text-zinc-500">No hay notificaciones.</p>}</div><Link href="/admin/notifications" onClick={()=>setOpen(false)} className="mt-4 block text-center text-sm font-bold text-cande-700">Abrir centro</Link></section>}</>
}
