'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {usePathname} from 'next/navigation'
import {Bell,Check} from 'lucide-react'
import {useAuth} from '@/components/auth-provider'
import {supabase} from '@/lib/supabase'
const STORAGE_KEY='cande-driver-alerted-requests'
export function DriverAlerts(){
 const pathname=usePathname(),{user}=useAuth(),[enabled,setEnabled]=useState(false),[testing,setTesting]=useState(false),[target,setTarget]=useState<HTMLElement|null>(null)
 const audio=useRef<AudioContext|null>(null),seen=useRef<Set<string>>(new Set()),nodes=useRef<OscillatorNode[]>([]),activeRequest=useRef<string|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null)
 const stop=useCallback(()=>{nodes.current.forEach(n=>{try{n.stop()}catch{}});nodes.current=[];if(timer.current)clearTimeout(timer.current);timer.current=null;speechSynthesis?.cancel();navigator.vibrate?.(0);activeRequest.current=null},[])
 const chime=useCallback((duration=8)=>{const context=audio.current;if(!context)return;const notes=[659,880,1047,880];for(let offset=0;offset<duration;offset+=1.35)notes.forEach((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime+offset+index*.16;oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.38,start+.025);gain.gain.exponentialRampToValueAtTime(.0001,start+.28);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+.3);nodes.current.push(oscillator)});setTimeout(()=>{const voice=new SpeechSynthesisUtterance('Cande, nuevo pedido');voice.lang='es-MX';voice.rate=.88;voice.pitch=1.08;voice.volume=1;speechSynthesis.speak(voice)},850)},[])
 const alertPhone=useCallback(async(id:string,orderNumber?:number)=>{if(seen.current.has(id))return;seen.current.add(id);sessionStorage.setItem(STORAGE_KEY,JSON.stringify([...seen.current].slice(-100)));activeRequest.current=id;chime(8);navigator.vibrate?.([500,180,500,180,800,250,500,180,500,180,900]);timer.current=setTimeout(stop,9000);if(Notification.permission==='granted'){const registration=await navigator.serviceWorker?.ready;await registration?.showNotification('Nueva entrega Cande',{body:orderNumber?`Solicitud CAN-${String(orderNumber).padStart(6,'0')}`:'Hay una nueva solicitud disponible',icon:'/icons/cande-driver-192.png',badge:'/icons/cande-driver-192.png',tag:`delivery-${id}`,data:{url:'/driver'}})}},[chime,stop])
 async function enable(){stop();setTesting(true);audio.current||=new AudioContext();await audio.current.resume();if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();setEnabled(true);chime(2.2);navigator.vibrate?.([300,120,300]);setTimeout(()=>{stop();setTesting(false)},2500)}
 useEffect(()=>{try{seen.current=new Set(JSON.parse(sessionStorage.getItem(STORAGE_KEY)||'[]'))}catch{seen.current=new Set()}},[])
 useEffect(()=>{if(pathname!=='/driver')return;let host:HTMLDivElement|null=null;const place=()=>{const metrics=document.querySelector('section.mt-3.grid.grid-cols-3');if(!metrics||host)return;host=document.createElement('div');metrics.parentElement?.insertBefore(host,metrics);setTarget(host)},observer=new MutationObserver(place);place();observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();host?.remove();setTarget(null)}},[pathname])
 useEffect(()=>{if(!enabled||!supabase||!user||user.app_metadata.role!=='DRIVER')return;const client=supabase,channel=client.channel(`driver-audio-alerts-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'delivery_requests'},async payload=>{const request=payload.new as {id:string};const{data}=await client.rpc('driver_available_requests'),visible=(data||[]).find((item:any)=>item.id===request.id);if(visible)await alertPhone(request.id,visible.order_number)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'delivery_requests'},payload=>{if(activeRequest.current===(payload.new as {id:string}).id)stop()}).subscribe();return()=>{stop();client.removeChannel(channel)}},[alertPhone,enabled,stop,user])
 if(!target||!user||user.app_metadata.role!=='DRIVER')return null
 return createPortal(<div className="mt-3"><button type="button" onClick={enable} className={`flex min-h-11 w-full items-center justify-center gap-2 rounded-md border px-4 py-3 text-sm font-black ${enabled?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-cande-200 bg-white text-cande-700'}`}>{enabled?<Check size={18}/>:<Bell size={18}/>} {enabled?'🟢 🔔 Alertas activadas':testing?'Probando sonido y vibracion...':'🔔 Activar alertas'}</button></div>,target)
}
