'use client'

import Image from 'next/image'
import Link from 'next/link'
import QRCode from 'qrcode'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, Copy, Gift, Link2, MessageCircle, QrCode, Share2, Users } from 'lucide-react'
import { useAuth } from '@/components/auth-provider'
import { supabase } from '@/lib/supabase'

type ReferralItem={id:string;name:string;status:string;registeredAt:string;qualifiedAt:string|null;rewardRedemptionId:string|null}
type EligibleProduct={id:string;name:string;image:string|null}
type Dashboard={code:string;registered:number;qualified:number;rewardsEarned:number;rewardsAvailable:number;rewardSize:string;eligibleProducts:EligibleProduct[];referrals:ReferralItem[]}

const labels:Record<string,string>={REGISTERED:'Falta su primera compra',FIRST_ORDER_PENDING:'Primera compra en proceso',QUALIFIED:'¡Recompensa disponible!',REWARD_CREATED:'Recompensa generada',REDEEMED:'Recompensa utilizada',INVALID:'Invitación no válida'}

export function ReferralProgram({compact=false}:{compact?:boolean}){
 const{user}=useAuth(),[data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[qr,setQr]=useState(''),[choosing,setChoosing]=useState<ReferralItem|null>(null),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{if(!supabase||!user){setLoading(false);return}setLoading(true);const{data:result}=await supabase.rpc('referral_dashboard');setData(result as Dashboard|null);setLoading(false)},[user])
 useEffect(()=>{load()},[load])
 const link=useMemo(()=>data?.code&&typeof window!=='undefined'?`${window.location.origin}/?ref=${encodeURIComponent(data.code)}`:'',[data?.code])
 useEffect(()=>{if(link&&!compact)QRCode.toDataURL(link,{width:640,margin:2,color:{dark:'#4b1325',light:'#fffafb'}}).then(setQr)},[compact,link])
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setNotice(`${label} copiado ✓`);setTimeout(()=>setNotice(''),2200)}
 function whatsapp(){const message=`🍓 Te invito a probar Fresas con Crema Cande.\n\nEntra a la app con mi enlace y haz tu primer pedido.\n\nMi código de invitación es: ${data?.code}\n\n👉 ${link}`;window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
 async function shareQr(){if(!qr)return;const blob=await(await fetch(qr)).blob(),file=new File([blob],`QR-Cande-${data?.code}.png`,{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'Mi invitación Cande',text:`Usa mi código ${data?.code}`,files:[file],url:link});else await copy(link,'Enlace')}
 async function claim(productId:string){if(!supabase||!choosing||busy)return;setBusy(true);const{error}=await supabase.rpc('claim_referral_reward',{p_referral_id:choosing.id,p_product_id:productId});setBusy(false);if(error){setNotice('No pudimos generar el premio. Intenta nuevamente.');return}setChoosing(null);setNotice('🎉 Tu premio ya aparece en Recompensas.');await load()}
 if(!user)return <section className="overflow-hidden rounded-lg bg-cande-900 p-6 text-white"><p className="text-xs font-black uppercase text-cande-200">🎁 Invita y gana</p><h2 className="mt-2 text-2xl font-black">Invita amigos y gana Fresas</h2><p className="mt-2 text-sm text-white/75">Crea tu cuenta, comparte tu código y gana unas Fresas Cande de 10 oz cuando tu amigo complete su primera compra.</p><Link href="/account?next=/account/referrals" className="mt-5 inline-flex rounded-full bg-cande-500 px-5 py-3 text-sm font-black">Crear mi código</Link></section>
 if(loading)return <section className="card p-5 text-sm text-zinc-500">Cargando tu código Cande…</section>
 if(!data)return <section className="card p-5 text-sm text-zinc-500">No pudimos cargar tus referidos.</section>
 const available=data.referrals.find(x=>x.status==='QUALIFIED')
 return <section className={compact?'overflow-hidden rounded-lg border border-cande-100 bg-gradient-to-br from-white to-cande-50 p-6':'space-y-5'}>
  <div className={compact?'':'overflow-hidden rounded-lg bg-cande-900 p-6 text-white'}><p className={`text-xs font-black uppercase ${compact?'text-cande-500':'text-cande-200'}`}>🎁 Invita y gana</p><h2 className="mt-2 text-2xl font-black">Invita amigos. Gana Fresas GRATIS 🍓</h2><p className={`mt-2 text-sm ${compact?'text-zinc-600':'text-white/75'}`}>Por cada amigo que complete su primera compra válida, cobrada y entregada, ganas unas Fresas Cande de {data.rewardSize}.</p><div className={`mt-5 rounded-md p-4 ${compact?'bg-white':'bg-white/10'}`}><span className={`text-xs font-bold ${compact?'text-zinc-500':'text-white/60'}`}>Tu código Cande</span><strong className={`mt-1 block break-all text-2xl ${compact?'text-cande-800':'text-white'}`}>{data.code}</strong><button onClick={()=>copy(data.code,'Código')} className={`mt-3 inline-flex min-h-11 items-center gap-2 rounded-full px-4 text-sm font-black ${compact?'bg-cande-100 text-cande-700':'bg-white text-cande-700'}`}><Copy size={17}/>Copiar código</button></div><button onClick={whatsapp} className="mt-4 flex min-h-13 w-full items-center justify-center gap-2 rounded-full bg-[#1fa855] px-5 py-3 font-black text-white"><MessageCircle size={20}/>Invitar por WhatsApp</button>{compact&&<Link href="/account/referrals" className="mt-3 flex min-h-12 items-center justify-center gap-2 rounded-full border border-cande-200 bg-white font-black text-cande-700">Ver mi código y QR</Link>}</div>
  {notice&&<p role="status" className="rounded-md bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{notice}</p>}
  {!compact&&<><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric icon={Users} label="Amigos registrados" value={data.registered}/><Metric icon={Check} label="Ya compraron" value={data.qualified}/><Metric icon={Gift} label="Premios ganados" value={data.rewardsEarned}/><Metric icon={Gift} label="Disponibles" value={data.rewardsAvailable}/></section><section className="card p-5"><h3 className="font-black">Tu enlace para invitar</h3><p className="mt-2 break-all rounded-md bg-cande-50 p-3 text-sm text-cande-800">{link}</p><button onClick={()=>copy(link,'Enlace')} className="mt-3 flex min-h-11 items-center gap-2 rounded-full border border-cande-200 px-4 text-sm font-black text-cande-700"><Link2 size={17}/>Copiar enlace</button></section><section className="card p-5 text-center"><h3 className="font-black">Tu QR Cande</h3><p className="mt-1 text-sm text-zinc-500">Pide a tus amigos que escaneen este código.</p>{qr?<Image src={qr} alt={`QR del código ${data.code}`} width={260} height={260} unoptimized className="mx-auto mt-4 rounded-md"/>:<div className="mx-auto mt-4 grid h-52 w-52 place-items-center bg-cande-50"><QrCode/></div>}<button onClick={shareQr} className="mx-auto mt-3 flex min-h-11 items-center gap-2 rounded-full border border-cande-200 px-4 text-sm font-black text-cande-700"><Share2 size={17}/>Compartir QR</button></section>{available&&<section className="rounded-lg border-2 border-cande-400 bg-cande-50 p-6 text-center"><h3 className="text-2xl font-black">🎉 ¡Ganaste unas Fresas GRATIS!</h3><p className="mt-2 text-sm text-cande-800">Tu amigo completó su primera compra.</p><button onClick={()=>setChoosing(available)} className="mt-5 min-h-13 w-full rounded-full bg-cande-500 px-5 font-black text-white">Elegir mi sabor 🍓</button></section>}<section><h3 className="text-xl font-black">Tus referidos</h3><div className="mt-3 space-y-3">{data.referrals.map(item=><article key={item.id} className="card flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-cande-100 font-black text-cande-700">{item.name.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><strong>{item.name}</strong><p className={`mt-1 text-xs font-bold ${item.status==='INVALID'?'text-red-600':item.status==='QUALIFIED'?'text-green-700':'text-zinc-500'}`}>{labels[item.status]||'En seguimiento'}</p></div>{item.status==='QUALIFIED'&&<button onClick={()=>setChoosing(item)} className="rounded-full bg-cande-500 px-3 py-2 text-xs font-black text-white">Elegir sabor</button>}</article>)}{!data.referrals.length&&<p className="rounded-md border border-dashed bg-white p-6 text-sm text-zinc-500">Todavía no tienes amigos registrados con tu código.</p>}</div></section></>}
  {choosing&&<div className="fixed inset-0 z-[70] overflow-y-auto bg-black/55 p-4"><section className="mx-auto mt-16 max-w-lg rounded-lg bg-[#fffafb] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase text-cande-500">Tu premio</p><h3 className="text-2xl font-black">Elige tu sabor</h3></div><button onClick={()=>setChoosing(null)} className="grid h-11 w-11 place-items-center rounded-full bg-white">×</button></div><div className="mt-5 grid grid-cols-2 gap-3">{data.eligibleProducts.map(product=><button disabled={busy} key={product.id} onClick={()=>claim(product.id)} className="overflow-hidden rounded-md border bg-white text-left disabled:opacity-50"><span className="relative block h-32 bg-cande-50">{product.image&&<Image src={product.image} alt={product.name} fill className="object-contain"/>}</span><strong className="block p-3 text-sm">{product.name} · {data.rewardSize}</strong></button>)}</div></section></div>}
 </section>
}

function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <article className="card p-4"><Icon size={18} className="text-cande-500"/><strong className="mt-3 block text-2xl">{value}</strong><span className="text-xs font-bold text-zinc-500">{label}</span></article>}
