'use client'

import {createContext,useCallback,useContext,useEffect,useState} from 'react'
import {products as seedProducts,toppings as seedToppings,rewards as seedRewards,promotions as seedPromotions,Product,Promotion,sizes} from '@/lib/data'
import {supabase} from '@/lib/supabase'

export type Availability='active'|'sold_out'|'hidden'
export type ManagedProduct=Product&{active:boolean;availability:Availability;category:string;ingredients:string[];availableSizes:Record<string,boolean>;toppingIds:string[];specialty:boolean;featured:boolean;favorite:boolean;sortOrder:number}
export type ManagedTopping={id:string;name:string;price:number;active:boolean;productIds:string[]}
export type ManagedReward={name:string;points:number;icon:string;active:boolean}
export type ManagedPromotion=Promotion&{active:boolean;productIds:string[];discountPesos:number;discountPercent:number;extraPoints:number;doublePoints:boolean;freeShipping:boolean;comboPrice:number|null}
export type StoreConfig={products:ManagedProduct[];toppings:ManagedTopping[];rewards:ManagedReward[];promotions:ManagedPromotion[];shippingFee:number;pointsPerPeso:number;hero:{title:string;description:string;image:string;button:string}}

const initial:StoreConfig={products:seedProducts.map((p,i)=>({...p,active:true,availability:'active',category:'Fresas con crema',ingredients:['Fresa','Crema'],availableSizes:Object.fromEntries(sizes.map(s=>[s,true])),toppingIds:[],specialty:i<3,featured:i<4,favorite:i<3,sortOrder:i})),toppings:seedToppings.map((t,i)=>({id:`seed-${i}`,...t,active:true,productIds:[]})),rewards:seedRewards.map(r=>({...r,active:true})),promotions:seedPromotions.map(p=>({...p,active:true,productIds:[],discountPesos:0,discountPercent:0,extraPoints:0,doublePoints:p.id.includes('double'),freeShipping:false,comboPrice:null})),shippingFee:35,pointsPerPeso:.1,hero:{title:'Tu antojo tiene recompensa',description:'Fresas frescas, crema de la casa y algo rico esperándote.',image:'/images/cande-classic.png',button:'Ver menú'}}
type StoreValue={config:StoreConfig;loading:boolean;refresh:()=>Promise<void>;save:(c:StoreConfig)=>Promise<void>;saveProduct:(p:ManagedProduct)=>Promise<void>;saveTopping:(t:ManagedTopping)=>Promise<void>;uploadProductImage:(file:File,productId:string)=>Promise<string>}
const C=createContext<StoreValue|null>(null)

export function StoreProvider({children}:{children:React.ReactNode}){
 const[config,setConfig]=useState(initial),[loading,setLoading]=useState(true)
 const refresh=useCallback(async()=>{if(!supabase){setLoading(false);return}const[p,t,tp,r,s]=await Promise.all([
  supabase.from('products').select('id,name,description,image_url,active,availability_status,category,included_ingredients,specialty,featured,favorite,sort_order,product_sizes(name,price,active)').order('sort_order'),
  supabase.from('toppings').select('id,name,price,active').order('name'),
  supabase.from('topping_products').select('topping_id,product_id'),
  supabase.from('rewards').select('name,points_cost,active').order('sort_order'),
  supabase.from('store_settings').select('shipping_fee').eq('id','main').single()
 ]);const error=p.error||t.error||tp.error||r.error||s.error;if(error){setLoading(false);throw error}const links=tp.data||[]
  setConfig(current=>({...current,products:(p.data||[]).map((row:any)=>({id:row.id,name:row.name,description:row.description,image:row.image_url||'/images/cande-classic.png',prices:Object.fromEntries(sizes.map(size=>[size,Number(row.product_sizes.find((x:any)=>x.name===size)?.price||0)])),active:row.active,availability:row.availability_status||'active',category:row.category||'Fresas con crema',ingredients:Array.isArray(row.included_ingredients)?row.included_ingredients:[],availableSizes:Object.fromEntries(sizes.map(size=>[size,Boolean(row.product_sizes.find((x:any)=>x.name===size)?.active)])),toppingIds:links.filter((x:any)=>x.product_id===row.id).map((x:any)=>x.topping_id),specialty:row.specialty,featured:row.featured,favorite:row.favorite,sortOrder:row.sort_order})),toppings:(t.data||[]).map((row:any)=>({id:row.id,name:row.name,price:Number(row.price),active:row.active,productIds:links.filter((x:any)=>x.topping_id===row.id).map((x:any)=>x.product_id)})),rewards:(r.data||[]).map((row:any,i:number)=>({name:row.name,points:row.points_cost,active:row.active,icon:['sparkles','ticket','gift','crown'][i]||'gift'})),shippingFee:Number(s.data?.shipping_fee||35)}));setLoading(false)
 },[])
 useEffect(()=>{refresh().catch(()=>setLoading(false));if(!supabase)return;const channel=supabase.channel('catalog-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'product_sizes'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'toppings'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'topping_products'},()=>refresh()).subscribe();return()=>{supabase?.removeChannel(channel)}},[refresh])
 async function saveProduct(p:ManagedProduct){if(!supabase)throw new Error('Supabase no está configurado');const recipe=p.ingredients.map(name=>({name,quantity:null,unit:null}));const{error}=await supabase.rpc('admin_save_product',{p_product:{id:p.id,name:p.name,description:p.description,image_url:p.image,availability_status:p.availability,category:p.category,included_ingredients:p.ingredients,specialty:p.specialty,featured:p.featured,favorite:p.favorite,sort_order:p.sortOrder},p_sizes:sizes.map(name=>({name,price:Number(p.prices[name]||0),active:Boolean(p.availableSizes[name])})),p_topping_ids:p.toppingIds,p_recipe:recipe});if(error)throw error;await refresh()}
 async function saveTopping(t:ManagedTopping){if(!supabase)throw new Error('Supabase no está configurado');const{error}=await supabase.rpc('admin_save_topping',{p_id:t.id.startsWith('new-')?null:t.id,p_name:t.name,p_price:Number(t.price),p_active:t.active,p_product_ids:t.productIds});if(error)throw error;await refresh()}
 async function uploadProductImage(file:File,productId:string){if(!supabase)throw new Error('Supabase no está configurado');if(!file.type.startsWith('image/'))throw new Error('Selecciona una imagen válida');if(file.size>5*1024*1024)throw new Error('La imagen debe pesar menos de 5 MB');const extension=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${productId}/${crypto.randomUUID()}.${extension}`,{error}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
 async function save(next:StoreConfig){if(!supabase)throw new Error('Supabase no está configurado');await Promise.all(next.products.map(saveProduct));await Promise.all(next.toppings.map(saveTopping));const{error}=await supabase.from('store_settings').upsert({id:'main',shipping_fee:next.shippingFee,updated_at:new Date().toISOString()});if(error)throw error;await refresh()}
 return <C.Provider value={{config,loading,refresh,save,saveProduct,saveTopping,uploadProductImage}}>{children}</C.Provider>
}
export function useStore(){const value=useContext(C);if(!value)throw new Error('useStore fuera de StoreProvider');return value}
