'use client'

import {createContext,useCallback,useContext,useEffect,useState} from 'react'
import {products as seedProducts,toppings as seedToppings,rewards as seedRewards,promotions as seedPromotions,Product,Promotion,sizes} from '@/lib/data'
import {supabase} from '@/lib/supabase'

export type Availability='active'|'sold_out'|'hidden'
export type RecipeComponent={inventoryItemId?:string;name:string;quantity:number;unit:string;unitCost:number}
export type ManagedProduct=Product&{active:boolean;availability:Availability;category:string;ingredients:string[];availableSizes:Record<string,boolean>;toppingIds:string[];specialty:boolean;featured:boolean;favorite:boolean;sortOrder:number;productType:'product'|'combo';recipes:Record<string,RecipeComponent[]>}
export type ManagedTopping={id:string;name:string;price:number;active:boolean;productIds:string[]}
export type ManagedReward={name:string;points:number;icon:string;active:boolean}
export type ManagedPromotion=Promotion&{active:boolean;productIds:string[];discountPesos:number;discountPercent:number;extraPoints:number;doublePoints:boolean;freeShipping:boolean;comboPrice:number|null}
export type InventoryItem={id:string;name:string;unit:string;unitCost:number;stockQuantity:number;active:boolean}
export type StoreConfig={products:ManagedProduct[];toppings:ManagedTopping[];inventory:InventoryItem[];rewards:ManagedReward[];promotions:ManagedPromotion[];shippingFee:number;pointsPerPeso:number;hero:{title:string;description:string;image:string;button:string}}

const initial:StoreConfig={products:seedProducts.map((p,i)=>({...p,active:true,availability:'active',category:'Fresas con crema',ingredients:['Fresa','Crema'],availableSizes:Object.fromEntries(sizes.map(s=>[s,true])),toppingIds:[],specialty:i<3,featured:i<4,favorite:i<3,sortOrder:i,productType:'product',recipes:{}})),toppings:seedToppings.map((t,i)=>({id:`seed-${i}`,...t,active:true,productIds:[]})),inventory:[],rewards:seedRewards.map(r=>({...r,active:true})),promotions:seedPromotions.map(p=>({...p,active:true,productIds:[],discountPesos:0,discountPercent:0,extraPoints:0,doublePoints:p.id.includes('double'),freeShipping:false,comboPrice:null})),shippingFee:35,pointsPerPeso:.1,hero:{title:'Tu antojo tiene recompensa',description:'Fresas frescas, crema de la casa y algo rico esperándote.',image:'/images/cande-classic.png',button:'Ver menú'}}
type StoreValue={config:StoreConfig;loading:boolean;refresh:()=>Promise<void>;save:(c:StoreConfig)=>Promise<void>;saveProduct:(p:ManagedProduct)=>Promise<void>;saveTopping:(t:ManagedTopping)=>Promise<void>;uploadProductImage:(file:File,productId:string)=>Promise<string>}
const C=createContext<StoreValue|null>(null)

export function StoreProvider({children}:{children:React.ReactNode}){
 const[config,setConfig]=useState(initial),[loading,setLoading]=useState(true)
 const refresh=useCallback(async()=>{if(!supabase){setLoading(false);return}const[p,t,tp,inv,ri,r,s,pr]=await Promise.all([
  supabase.from('products').select('id,name,description,image_url,active,availability_status,category,included_ingredients,specialty,featured,favorite,sort_order,product_type,product_sizes(name,price,active)').order('sort_order'),
  supabase.from('toppings').select('id,name,price,active').order('name'),supabase.from('topping_products').select('topping_id,product_id'),
  supabase.from('inventory_items').select('id,name,unit,unit_cost,stock_quantity,active').order('name'),
  supabase.from('product_recipe_items').select('product_id,size_name,inventory_item_id,quantity'),
  supabase.from('rewards').select('name,points_cost,active').order('sort_order'),supabase.from('store_settings').select('shipping_fee').eq('id','main').single(),
  supabase.from('promotions').select('*').eq('status','active').order('starts_at',{ascending:false})
 ]);const critical=p.error||t.error||tp.error||r.error||s.error;if(critical){setLoading(false);throw critical}const links=tp.data||[],inventory=(inv.data||[]).map((x:any)=>({id:x.id,name:x.name,unit:x.unit,unitCost:Number(x.unit_cost),stockQuantity:Number(x.stock_quantity),active:x.active}));
  const managedProducts=(p.data||[]).map((row:any)=>{const offerings=row.product_sizes||[];const recipes:Record<string,RecipeComponent[]>={};for(const offering of offerings){recipes[offering.name]=(ri.data||[]).filter((x:any)=>x.product_id===row.id&&x.size_name===offering.name).map((x:any)=>{const item=inventory.find(i=>i.id===x.inventory_item_id);return{inventoryItemId:x.inventory_item_id,name:item?.name||'Ingrediente',quantity:Number(x.quantity),unit:item?.unit||'unidad',unitCost:item?.unitCost||0}})}return{id:row.id,name:row.name,description:row.description,image:row.image_url||'/images/cande-classic.png',prices:Object.fromEntries(offerings.map((x:any)=>[x.name,Number(x.price)])),active:row.active,availability:row.availability_status||'active',category:row.category||'Fresas con crema',ingredients:Array.isArray(row.included_ingredients)?row.included_ingredients:[],availableSizes:Object.fromEntries(offerings.map((x:any)=>[x.name,Boolean(x.active)])),toppingIds:links.filter((x:any)=>x.product_id===row.id).map((x:any)=>x.topping_id),specialty:row.specialty,featured:row.featured,favorite:row.favorite,sortOrder:row.sort_order,productType:row.product_type||'product',recipes} as ManagedProduct});
  setConfig(current=>({...current,inventory,products:managedProducts,
   toppings:(t.data||[]).map((row:any)=>({id:row.id,name:row.name,price:Number(row.price),active:row.active,productIds:links.filter((x:any)=>x.topping_id===row.id).map((x:any)=>x.product_id)})),rewards:(r.data||[]).map((row:any,i:number)=>({name:row.name,points:row.points_cost,active:row.active,icon:['sparkles','ticket','gift','crown'][i]||'gift'})),shippingFee:Number(s.data?.shipping_fee||35),promotions:pr.error?current.promotions:(pr.data||[]).map((x:any)=>({id:x.id,eyebrow:'Promoción vigente',title:x.title,description:x.description,image:x.image_url||'/images/cande-special.png',startsAt:x.starts_at,endsAt:x.ends_at,ctaHref:'/menu',active:true,productIds:x.product_ids||[],discountPesos:Number(x.discount_amount||0),discountPercent:Number(x.discount_percent||0),extraPoints:x.extra_points||0,doublePoints:x.double_points,freeShipping:x.free_shipping,comboPrice:x.combo_price===null?null:Number(x.combo_price)}))}));setLoading(false)
 },[])
 useEffect(()=>{refresh().catch(()=>setLoading(false));if(!supabase)return;const channel=supabase.channel('catalog-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'product_sizes'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'toppings'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'topping_products'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'promotions'},()=>refresh()).subscribe();return()=>{supabase?.removeChannel(channel)}},[refresh])
 async function saveProduct(p:ManagedProduct){if(!supabase)throw new Error('Supabase no está configurado');const sizeNames=Object.keys(p.availableSizes);const{error}=await supabase.rpc('admin_save_product',{p_product:{id:p.id,name:p.name,description:p.description,image_url:p.image,availability_status:p.availability,category:p.category,included_ingredients:p.ingredients,specialty:p.specialty,featured:p.featured,favorite:p.favorite,sort_order:p.sortOrder},p_sizes:sizeNames.map(name=>({name,price:Number(p.prices[name]||0),active:Boolean(p.availableSizes[name])})),p_topping_ids:p.toppingIds,p_recipe:[]});if(error)throw error;const typeUpdate=await supabase.from('products').update({product_type:p.productType}).eq('id',p.id);if(typeUpdate.error)throw typeUpdate.error;
  for(const sizeName of sizeNames){const components=[];for(const component of p.recipes[sizeName]||[]){const saved=await supabase.rpc('admin_upsert_inventory_item',{p_name:component.name,p_unit:component.unit,p_unit_cost:Number(component.unitCost||0)});if(saved.error)throw saved.error;components.push({inventory_item_id:saved.data,quantity:Number(component.quantity)})}const recipe=await supabase.rpc('admin_save_recipe',{p_product_id:p.id,p_size_name:sizeName,p_components:components});if(recipe.error)throw recipe.error}await refresh()}
 async function saveTopping(t:ManagedTopping){if(!supabase)throw new Error('Supabase no está configurado');const{error}=await supabase.rpc('admin_save_topping',{p_id:t.id.startsWith('new-')?null:t.id,p_name:t.name,p_price:Number(t.price),p_active:t.active,p_product_ids:t.productIds});if(error)throw error;await refresh()}
 async function uploadProductImage(file:File,productId:string){if(!supabase)throw new Error('Supabase no está configurado');if(!file.type.startsWith('image/'))throw new Error('Selecciona una imagen válida');if(file.size>5*1024*1024)throw new Error('La imagen debe pesar menos de 5 MB');const extension=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${productId}/${crypto.randomUUID()}.${extension}`,{error}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
 async function save(next:StoreConfig){if(!supabase)throw new Error('Supabase no está configurado');const{error}=await supabase.from('store_settings').upsert({id:'main',shipping_fee:next.shippingFee,updated_at:new Date().toISOString()});if(error)throw error;await refresh()}
 return <C.Provider value={{config,loading,refresh,save,saveProduct,saveTopping,uploadProductImage}}>{children}</C.Provider>
}
export function useStore(){const value=useContext(C);if(!value)throw new Error('useStore fuera de StoreProvider');return value}
