'use client'
import {createContext,useContext,useEffect,useMemo,useState} from 'react'
import {products as seedProducts,toppings as seedToppings,rewards as seedRewards,promotions as seedPromotions,Product,Promotion} from '@/lib/data'
import {supabase} from '@/lib/supabase'

export type ManagedProduct=Product&{active:boolean;specialty:boolean;featured:boolean;favorite:boolean;sortOrder:number}
export type ManagedTopping={name:string;price:number;active:boolean;productIds:string[]}
export type ManagedReward={name:string;points:number;icon:string;active:boolean}
export type ManagedPromotion=Promotion&{active:boolean;productIds:string[];discountPesos:number;discountPercent:number;extraPoints:number;doublePoints:boolean;freeShipping:boolean;comboPrice:number|null}
export type StoreConfig={products:ManagedProduct[];toppings:ManagedTopping[];rewards:ManagedReward[];promotions:ManagedPromotion[];shippingFee:number;pointsPerPeso:number;hero:{title:string;description:string;image:string;button:string}}
const initial:StoreConfig={products:seedProducts.map((p,i)=>({...p,active:true,specialty:i<3,featured:i<4,favorite:i<3,sortOrder:i})),toppings:seedToppings.map(t=>({...t,active:true,productIds:[]})),rewards:seedRewards.map(r=>({...r,active:true})),promotions:seedPromotions.map(p=>({...p,active:true,productIds:[],discountPesos:0,discountPercent:0,extraPoints:0,doublePoints:p.id.includes('double'),freeShipping:false,comboPrice:null})),shippingFee:35,pointsPerPeso:.1,hero:{title:'Tu antojo tiene recompensa',description:'Fresas frescas, crema de la casa y algo rico esperándote.',image:'/images/cande-classic.png',button:'Ver menú'}}
const C=createContext<{config:StoreConfig;save:(c:StoreConfig)=>void}|null>(null)
export function StoreProvider({children}:{children:React.ReactNode}){const[config,setConfig]=useState(initial);useEffect(()=>{if(!supabase)return;Promise.all([supabase.from('products').select('id,name,description,image_url,active,specialty,featured,favorite,sort_order,product_sizes(name,price)').order('sort_order'),supabase.from('toppings').select('name,price,active').order('name'),supabase.from('rewards').select('name,points_cost,active').order('sort_order'),supabase.from('store_settings').select('shipping_fee').eq('id','main').single()]).then(([p,t,r,s])=>setConfig(current=>({...current,products:(p.data||[]).map((row:any)=>({id:row.id,name:row.name,description:row.description,image:row.image_url||'/images/cande-classic.png',prices:Object.fromEntries(row.product_sizes.map((size:any)=>[size.name,Number(size.price)])),active:row.active,specialty:row.specialty,featured:row.featured,favorite:row.favorite,sortOrder:row.sort_order})),toppings:(t.data||[]).map((row:any)=>({name:row.name,price:Number(row.price),active:row.active,productIds:[]})),rewards:(r.data||[]).map((row:any,i:number)=>({name:row.name,points:row.points_cost,active:row.active,icon:['sparkles','ticket','gift','crown'][i]||'gift'})),shippingFee:Number(s.data?.shipping_fee||35)})))},[]);async function persist(next:StoreConfig){if(!supabase)return;await supabase.from('products').upsert(next.products.map(p=>({id:p.id,name:p.name,description:p.description,image_url:p.image,active:p.active,specialty:p.specialty,featured:p.featured,favorite:p.favorite,sort_order:p.sortOrder})));for(const p of next.products)await supabase.from('product_sizes').upsert(Object.entries(p.prices).map(([name,price])=>({product_id:p.id,name,ounces:Number(name.split(' ')[0]),price})),{onConflict:'product_id,name'});await supabase.from('toppings').upsert(next.toppings.map(t=>({name:t.name,price:t.price,active:t.active})),{onConflict:'name'});await supabase.from('store_settings').upsert({id:'main',shipping_fee:next.shippingFee,updated_at:new Date().toISOString()})}function save(next:StoreConfig){setConfig(next);persist(next);dispatchEvent(new CustomEvent('cande-store-updated',{detail:next}))}return <C.Provider value={{config,save}}>{children}</C.Provider>}
export function useStore(){const value=useContext(C);if(!value)throw new Error('useStore fuera de StoreProvider');return value}
