'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {CheckCircle2,Clock3,ReceiptText} from 'lucide-react'
import {useAuth} from '@/components/auth-provider'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'

type Order={id:string;order_number:number;created_at:string;total:number;status:string;order_items:{product_name:string;size_name:string;quantity:number}[]}
const labels:Record<string,string>={pending:'Recibido',confirmed:'Confirmado',preparing:'Preparando',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado'}
export default function Orders(){const{user,loading}=useAuth();const[orders,setOrders]=useState<Order[]>([]),[busy,setBusy]=useState(true)
 useEffect(()=>{if(!user||!supabase){setBusy(false);return}const load=()=>supabase!.from('orders').select('id,order_number,created_at,total,status,order_items(product_name,size_name,quantity)').order('created_at',{ascending:false}).then(({data})=>{setOrders((data||[])as unknown as Order[]);setBusy(false)});load();const channel=supabase.channel(`customer-orders-${user.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'orders',filter:`customer_id=eq.${user.id}`},load).subscribe();return()=>{supabase?.removeChannel(channel)}},[user])
 if(loading||busy)return <main className="page"><p className="text-center text-sm text-zinc-500">Cargando pedidos…</p></main>
 if(!user)return <main className="page max-w-xl text-center"><ReceiptText className="mx-auto text-cande-500" size={34}/><h1 className="mt-4 text-3xl font-black">Tu historial te espera</h1><p className="mt-2 text-sm text-zinc-500">Inicia sesión para ver únicamente tus pedidos.</p><Link href="/account?next=/orders" className="mt-6 inline-flex rounded-full bg-cande-500 px-6 py-3 font-bold text-white">Iniciar sesión</Link></main>
 return <main className="page max-w-3xl"><p className="text-xs font-bold uppercase text-cande-500">Historial real</p><h1 className="mt-1 text-3xl font-black">Mis pedidos</h1><div className="mt-7 space-y-3">{orders.length?orders.map(o=>{const delivered=o.status==='delivered';return <article key={o.id} className="card p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><span className={`grid h-10 w-10 place-items-center rounded-full ${delivered?'bg-green-100 text-green-700':'bg-cande-100 text-cande-600'}`}>{delivered?<CheckCircle2 size={19}/>:<Clock3 size={19}/>}</span><div><h2 className="font-extrabold">CAN-{String(o.order_number).padStart(6,'0')}</h2><p className="text-xs text-zinc-500">{new Date(o.created_at).toLocaleString('es-MX')}</p></div></div><strong>{money(Number(o.total))}</strong></div><p className="mt-4 border-t border-cande-50 pt-4 text-sm text-zinc-600">{o.order_items.map(i=>`${i.quantity}x ${i.product_name} ${i.size_name}`).join(' · ')}</p><p className="mt-2 text-xs font-bold text-cande-600">{labels[o.status]||o.status}</p></article>}):<p className="card p-6 text-center text-sm text-zinc-500">Aún no tienes pedidos registrados.</p>}</div><Link href="/menu" className="mt-6 flex items-center justify-center gap-2 rounded-full bg-cande-500 py-3 font-bold text-white"><ReceiptText size={18}/>Hacer un pedido</Link></main>}
