'use client'
import { useCallback, useEffect, useState } from 'react'
import { Gift, ShoppingBag, TrendingUp, Users } from 'lucide-react'
import { money } from '@/lib/data'
import { supabase } from '@/lib/supabase'
type Item={id:string;code:string;referrer:string;referred:string;registeredAt:string;status:string;orderNumber:number|null;orderTotal:number|null;orderStatus:string|null;rewardCreatedAt:string|null;redeemedAt:string|null}
type Data={total:number;qualified:number;rewardsCreated:number;rewardsRedeemed:number;sales:number;items:Item[]}
const status:Record<string,string>={REGISTERED:'Registrado',FIRST_ORDER_PENDING:'Primera compra pendiente',QUALIFIED:'Compra calificada',REWARD_CREATED:'Premio generado',REDEEMED:'Premio utilizado',INVALID:'Inválido'}
export default function AdminReferrals(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState('');const load=useCallback(async()=>{if(!supabase)return;const{data:result,error:issue}=await supabase.rpc('admin_referral_dashboard');if(issue)setError('No pudimos cargar los referidos.');else setData(result as Data)},[]);useEffect(()=>{load();if(!supabase)return;const channel=supabase.channel('admin-referrals-live').on('postgres_changes',{event:'*',schema:'public',table:'referrals'},load).subscribe();return()=>{supabase?.removeChannel(channel)}},[load]);const rate=data?.total?Math.round(data.qualified/data.total*100):0;return <main className="min-h-screen bg-[#fffafb] px-4 pb-24 pt-24"><div className="mx-auto max-w-7xl"><header><p className="text-xs font-black uppercase text-cande-500">Crecimiento orgánico</p><h1 className="mt-1 text-3xl font-black">🎁 Referidos</h1><p className="mt-2 text-sm text-zinc-500">Registro, primera compra y premios con datos reales.</p></header>{error&&<p className="mt-4 rounded-md bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric icon={Users} label="Referidos" value={String(data?.total||0)}/><Metric icon={ShoppingBag} label="Ya compraron" value={String(data?.qualified||0)}/><Metric icon={TrendingUp} label="Conversión" value={`${rate}%`}/><Metric icon={Gift} label="Premios / canjes" value={`${data?.rewardsCreated||0} / ${data?.rewardsRedeemed||0}`}/><Metric icon={TrendingUp} label="Ventas referidas" value={money(Number(data?.sales||0))}/></section><section className="mt-8 space-y-3"><h2 className="text-xl font-black">Actividad</h2>{data?.items.map(item=><article key={item.id} className="card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{item.referrer}</strong><span className="mx-2 text-zinc-300">→</span><strong>{item.referred}</strong><p className="mt-1 text-xs text-zinc-500">Código {item.code} · {new Date(item.registeredAt).toLocaleDateString('es-MX')}</p></div><span className="rounded-full bg-cande-50 px-3 py-1 text-xs font-black text-cande-700">{status[item.status]||item.status}</span></div>{item.orderNumber&&<div className="mt-3 grid grid-cols-2 gap-2 rounded-md bg-zinc-50 p-3 text-xs sm:grid-cols-4"><span>Pedido <b>CAN-{String(item.orderNumber).padStart(6,'0')}</b></span><span>Importe <b>{money(Number(item.orderTotal||0))}</b></span><span>Estado <b>{item.orderStatus}</b></span><span>Premio <b>{item.redeemedAt?'Utilizado':item.rewardCreatedAt?'Generado':'Disponible'}</b></span></div>}</article>)}{data&&!data.items.length&&<p className="rounded-md border border-dashed bg-white p-7 text-sm text-zinc-500">Aún no hay invitaciones registradas.</p>}</section></div></main>}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <article className="card p-4"><Icon size={18} className="text-cande-500"/><strong className="mt-3 block text-lg">{value}</strong><p className="mt-1 text-xs font-bold text-zinc-500">{label}</p></article>}
