'use client'
import Link from 'next/link'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Bike,Clock3,Gift,Lightbulb,MapPin,ShoppingBag,Sparkles,TrendingUp,Users} from 'lucide-react'
import {money} from '@/lib/data'
import {supabase} from '@/lib/supabase'

type Order={id:string;customer_id:string;total:number;status:string;created_at:string;points_earned:number;address:any;order_items:{product_name:string;quantity:number}[]}
type Customer={id:string;created_at:string;points_balance:number}
type Assignment={status:string;fee:number;delivered_at:string|null}

export default function Insights(){
 const[orders,setOrders]=useState<Order[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{if(!supabase)return;const[o,c,a]=await Promise.all([supabase.from('orders').select('id,customer_id,total,status,created_at,points_earned,address,order_items(product_name,quantity)').order('created_at'),supabase.from('customers').select('id,created_at,points_balance'),supabase.from('delivery_assignments').select('status,fee,delivered_at')]);setOrders((o.data||[]) as unknown as Order[]);setCustomers((c.data||[]) as Customer[]);setAssignments((a.data||[]) as Assignment[]);setLoading(false)},[])
 useEffect(()=>{load();if(!supabase)return;const channel=supabase.channel('admin-insights-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'delivery_assignments'},load).subscribe();return()=>{supabase?.removeChannel(channel)}},[load])
 const data=useMemo(()=>analyze(orders,customers,assignments),[orders,customers,assignments])
 return <main className="min-h-screen bg-[#fffafb] px-4 pb-20 pt-24"><div className="mx-auto max-w-6xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-cande-600"><ArrowLeft size={17}/>Volver al dashboard</Link><p className="mt-6 text-xs font-bold uppercase text-cande-500">Datos reales de Supabase</p><h1 className="mt-1 text-3xl font-black">Resumen inteligente</h1><p className="mt-2 text-sm text-zinc-500">Interpretación automática de ventas, clientes, horarios y entregas.</p>{loading?<p className="mt-8 text-sm text-zinc-500">Analizando información…</p>:<><section className="mt-7 rounded-lg bg-cande-900 p-6 text-white"><div className="flex gap-3"><Sparkles className="shrink-0 text-cande-200"/><div><p className="text-xs font-bold uppercase text-cande-200">Resumen de hoy</p><h2 className="mt-2 text-2xl font-black leading-snug">Hoy vendiste {money(data.todaySales)} en {data.todayOrders} pedidos.</h2><p className="mt-3 leading-relaxed text-white/80">{data.narrative}</p></div></div></section><section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={TrendingUp} label="Ventas semanales" value={money(data.weekSales)} note={`${data.growth>=0?'+':''}${data.growth}% vs. semana anterior`}/><Metric icon={ShoppingBag} label="Pedidos" value={String(data.weekOrders)} note={`Ticket ${money(data.avgTicket)}`}/><Metric icon={Users} label="Clientes recurrentes" value={String(data.repeatCustomers)} note="Esta semana"/><Metric icon={Bike} label="Entregas completas" value={String(data.delivered)} note={`${data.activeDeliveries} activas`}/></section><section className="mt-8 grid gap-4 lg:grid-cols-2"><Insight icon={Lightbulb} title="Lo más importante" text={`${data.topProduct} es el producto con mayor movimiento. ${data.peakHour} concentra más pedidos.`}/><Insight icon={Gift} title="Recompra y Rewards" text={`${data.nearReward} clientes están a 30 🍓 o menos de una recompensa. ${data.inactiveCustomers} llevan más de 14 días sin comprar.`}/><Insight icon={MapPin} title="Zonas y entregas" text={`${data.topZone} es la zona con más pedidos a domicilio. El pago promedio a repartidores es ${money(data.avgDriverPay)}.`}/><Insight icon={Clock3} title="Horario operativo" text={`La hora más fuerte es ${data.peakHour}. Conviene preparar inventario y equipo antes de ese periodo.`}/></section><section className="card mt-8 p-6"><h2 className="text-xl font-black">Resumen semanal</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Line label="Ventas totales" value={money(data.weekSales)}/><Line label="Pedidos" value={String(data.weekOrders)}/><Line label="Ticket promedio" value={money(data.avgTicket)}/><Line label="🍓 entregadas" value={String(data.points)}/><Line label="Producto líder" value={data.topProduct}/><Line label="Horario más fuerte" value={data.peakHour}/></div></section></>}</div></main>
}

function analyze(all:Order[],customers:Customer[],assignments:Assignment[]){const valid=all.filter(o=>o.status!=='cancelled'),now=Date.now(),day=86400000,startToday=new Date().setHours(0,0,0,0),weekStart=startToday-((new Date().getDay()+6)%7)*day,previousStart=weekStart-7*day,today=valid.filter(o=>+new Date(o.created_at)>=startToday),week=valid.filter(o=>+new Date(o.created_at)>=weekStart),previous=valid.filter(o=>{const t=+new Date(o.created_at);return t>=previousStart&&t<weekStart}),sales=(rows:Order[])=>rows.reduce((n,o)=>n+Number(o.total),0),weekSales=sales(week),previousSales=sales(previous),productCounts=new Map<string,number>(),hourCounts=new Map<number,number>(),customerCounts=new Map<string,number>(),zones=new Map<string,number>();for(const o of week){customerCounts.set(o.customer_id,(customerCounts.get(o.customer_id)||0)+1);hourCounts.set(new Date(o.created_at).getHours(),(hourCounts.get(new Date(o.created_at).getHours())||0)+1);for(const i of o.order_items)productCounts.set(i.product_name,(productCounts.get(i.product_name)||0)+i.quantity);const zone=o.address?.address?.split(',')[0]?.trim();if(zone)zones.set(zone,(zones.get(zone)||0)+1)}const topProduct=[...productCounts].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sin ventas',hour=[...hourCounts].sort((a,b)=>b[1]-a[1])[0]?.[0],peakHour=hour===undefined?'Sin datos':`${hour}:00–${(hour+1)%24}:00`,repeatCustomers=[...customerCounts.values()].filter(n=>n>1).length,growth=previousSales?Number(((weekSales-previousSales)/previousSales*100).toFixed(1)):weekSales?100:0,delivered=assignments.filter(a=>a.status==='delivered').length,activeDeliveries=assignments.filter(a=>['accepted','heading_to_pickup','picked_up','delivering'].includes(a.status)).length,avgDriverPay=assignments.length?assignments.reduce((n,a)=>n+Number(a.fee||0),0)/assignments.length:0,nearReward=customers.filter(c=>[200,300].some(goal=>goal-c.points_balance>0&&goal-c.points_balance<=30)).length,inactiveCustomers=customers.filter(c=>{const last=valid.filter(o=>o.customer_id===c.id).sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at))[0];return last&&now-+new Date(last.created_at)>14*day}).length,topZone=[...zones].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sin datos';return{todaySales:sales(today),todayOrders:today.length,weekSales,weekOrders:week.length,avgTicket:week.length?weekSales/week.length:0,repeatCustomers,growth,topProduct,peakHour,points:week.reduce((n,o)=>n+Number(o.points_earned||0),0),delivered,activeDeliveries,avgDriverPay,nearReward,inactiveCustomers,topZone,narrative:`Las ventas ${growth>=0?'subieron':'bajaron'} ${Math.abs(growth)}% frente a la semana anterior. ${topProduct} fue el producto más vendido y la hora más fuerte fue ${peakHour}.`}}
function Metric({label,value,note,icon:Icon}:{label:string;value:string;note:string;icon:any}){return <article className="card p-4"><Icon size={18} className="text-cande-600"/><strong className="mt-3 block text-lg">{value}</strong><p className="mt-1 text-xs font-bold text-zinc-500">{label}</p><p className="mt-2 text-[11px] text-zinc-400">{note}</p></article>}
function Insight({title,text,icon:Icon}:{title:string;text:string;icon:any}){return <article className="card flex gap-4 p-5"><Icon className="shrink-0 text-cande-500"/><div><h2 className="font-black">{title}</h2><p className="mt-2 text-sm leading-relaxed text-zinc-600">{text}</p></div></article>}
function Line({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b border-cande-50 pb-3 text-sm"><span className="text-zinc-500">{label}</span><strong>{value}</strong></div>}
