'use client'
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,Boxes,PackagePlus,Plus,RefreshCw,ShoppingCart} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {money} from '@/lib/data'

type Item={id:string;name:string;unit:string;unit_cost:number;stock_quantity:number;active:boolean}
type Recipe={inventory_item_id:string;quantity:number;product_id:string;size_name:string}
type Order={created_at:string;status:string;order_items:{product_id:string;size_name:string;quantity:number}[]}
type Movement={id:string;inventory_item_id:string;movement_type:string;quantity:number;unit_cost:number;notes:string|null;created_at:string}

export default function Inventory(){
 const[items,setItems]=useState<Item[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]),[orders,setOrders]=useState<Order[]>([]),[movements,setMovements]=useState<Movement[]>([]),[name,setName]=useState(''),[unit,setUnit]=useState('kg'),[selected,setSelected]=useState<Item|null>(null),[quantity,setQuantity]=useState(0),[cost,setCost]=useState(0),[notes,setNotes]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{if(!supabase)return;const[i,r,o,m]=await Promise.all([supabase.from('inventory_items').select('*').order('name'),supabase.from('product_recipe_items').select('inventory_item_id,quantity,product_id,size_name'),supabase.from('orders').select('created_at,status,order_items(product_id,size_name,quantity)').eq('status','delivered').gte('created_at',new Date(Date.now()-7*86400000).toISOString()),supabase.from('inventory_movements').select('*').order('created_at',{ascending:false}).limit(30)]);setItems((i.data||[]) as Item[]);setRecipes((r.data||[]) as Recipe[]);setOrders((o.data||[]) as unknown as Order[]);setMovements((m.data||[]) as Movement[])},[])
 useEffect(()=>{load()},[load])
 const usage=useMemo(()=>{const result=new Map<string,number>();for(const order of orders)for(const line of order.order_items)for(const recipe of recipes.filter(r=>r.product_id===line.product_id&&r.size_name===line.size_name))result.set(recipe.inventory_item_id,(result.get(recipe.inventory_item_id)||0)+Number(recipe.quantity)*line.quantity);return result},[orders,recipes])
 async function create(e:FormEvent){e.preventDefault();if(!supabase||!name.trim())return;setBusy(true);const{error}=await supabase.rpc('admin_upsert_inventory_item',{p_name:name.trim(),p_unit:unit.trim(),p_unit_cost:0});setBusy(false);setNotice(error?error.message:'Insumo creado correctamente. Ahora registra una compra.');if(!error){setName('');await load()}}
 async function purchase(e:FormEvent){e.preventDefault();if(!supabase||!selected)return;setBusy(true);const{error}=await supabase.rpc('admin_record_inventory_purchase',{p_item_id:selected.id,p_quantity:quantity,p_unit_cost:cost,p_notes:notes});setBusy(false);setNotice(error?error.message:'Compra registrada y existencia actualizada.');if(!error){setSelected(null);setQuantity(0);setNotes('');await load()}}
 return <main className="mx-auto min-h-screen max-w-6xl bg-[#fffafb] px-4 pb-20 pt-24 sm:px-6"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-cande-600"><ArrowLeft size={17}/>Volver al dashboard</Link><header className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-cande-500">Operación diaria</p><h1 className="mt-1 text-3xl font-black">📦 Inventario</h1><p className="mt-2 text-sm text-zinc-500">Existencias, compras y consumo automático al entregar pedidos.</p></div><button onClick={load} className="flex h-11 items-center gap-2 rounded-full border bg-white px-4 text-sm font-bold"><RefreshCw size={17}/>Actualizar</button></header>{notice&&<button onClick={()=>setNotice('')} className="mt-5 w-full rounded-md bg-green-50 p-4 text-left text-sm font-bold text-green-800">{notice}</button>}
 <form onSubmit={create} className="card mt-6 grid gap-3 p-5 sm:grid-cols-[1fr_160px_auto]"><label><span className="label">Nuevo insumo</span><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Fresa"/></label><label><span className="label">Unidad</span><input className="input" value={unit} onChange={e=>setUnit(e.target.value)} placeholder="kg, L, pieza"/></label><button disabled={busy||!name.trim()} className="mt-auto flex h-12 items-center justify-center gap-2 rounded-full bg-cande-500 px-5 font-black text-white"><Plus size={18}/>Agregar</button></form>
 <section className="mt-7 grid gap-4 md:grid-cols-2">{items.map(item=>{const weekly=usage.get(item.id)||0,daily=weekly/7,recommended=Math.max(0,Math.ceil(daily*7-Number(item.stock_quantity))),low=daily>0&&Number(item.stock_quantity)<daily*3;return <article key={item.id} className={`card p-5 ${low?'border-2 border-amber-300':''}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-zinc-500">{item.unit}</p><h2 className="mt-1 text-xl font-black">{item.name}</h2></div><Boxes className="text-cande-500"/></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-md bg-cande-50 p-3"><strong className="text-2xl">{Number(item.stock_quantity).toLocaleString('es-MX')}</strong><p className="text-xs text-zinc-500">Existencia</p></div><div className="rounded-md bg-zinc-50 p-3"><strong>{money(Number(item.unit_cost))}</strong><p className="text-xs text-zinc-500">Costo por {item.unit}</p></div></div><p className={`mt-4 text-sm font-bold ${low?'text-amber-700':'text-zinc-600'}`}>{recipes.some(r=>r.inventory_item_id===item.id)?recommended>0?`Compra sugerida: ${recommended} ${item.unit} para 7 días.`:'Existencia suficiente según los últimos 7 días.':'Relaciona este insumo con las recetas de Productos.'}</p><button onClick={()=>{setSelected(item);setCost(Number(item.unit_cost))}} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cande-500 font-black text-white"><PackagePlus size={18}/>Registrar compra</button></article>})}{!items.length&&<div className="card p-8 text-center text-zinc-500"><ShoppingCart className="mx-auto mb-3 text-cande-400"/>Agrega tu primer insumo y después relaciónalo con las recetas de cada producto.</div>}</section>
 <section className="card mt-8 overflow-hidden"><h2 className="p-5 text-xl font-black">Movimientos recientes</h2><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-cande-50 text-xs uppercase text-zinc-500"><tr><th className="p-3">Fecha</th><th>Insumo</th><th>Tipo</th><th>Cantidad</th><th>Costo</th></tr></thead><tbody>{movements.map(m=><tr key={m.id} className="border-t"><td className="p-3">{new Date(m.created_at).toLocaleString('es-MX')}</td><td>{items.find(i=>i.id===m.inventory_item_id)?.name||'Insumo'}</td><td>{m.movement_type==='purchase'?'Compra':'Consumo'}</td><td className="font-bold">{Number(m.quantity).toLocaleString('es-MX')}</td><td>{money(Number(m.unit_cost))}</td></tr>)}</tbody></table></div></section>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={purchase} className="card w-full max-w-md p-6"><h2 className="text-2xl font-black">Compra de {selected.name}</h2><p className="mt-1 text-sm text-zinc-500">Se sumará a la existencia actual.</p><label className="mt-5 block"><span className="label">Cantidad ({selected.unit})</span><input required min="0.001" step="0.001" type="number" className="input" value={quantity||''} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="mt-3 block"><span className="label">Costo por {selected.unit}</span><input required min="0" step="0.01" type="number" className="input" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label className="mt-3 block"><span className="label">Notas</span><input className="input" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Proveedor o referencia"/></label><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>setSelected(null)} className="h-12 rounded-full border font-bold">Cancelar</button><button disabled={busy||quantity<=0} className="h-12 rounded-full bg-cande-500 font-black text-white">Guardar compra</button></div></form></div>}
 </main>
}
